/* JS */ gapi.loaded_0(function(_){var window=this;
_.m=function(a){throw a;};_.p=void 0;_.r=!0;_.s=null;_.u=!1;_.aa=function(){return function(a){return a}};_.v=function(){return function(){}};_.ba=function(a){return function(c){this[a]=c}};_.y=function(a){return function(){return this[a]}};_.ca=function(a){return function(){return a}};_.C=function(a,c,f){a=a.split(".");f=f||_.D;!(a[0]in f)&&f.execScript&&f.execScript("var "+a[0]);for(var g;a.length&&(g=a.shift());)!a.length&&(0,_.E)(c)?f[g]=c:f=f[g]?f[g]:f[g]={}};
_.da=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof window.Array)return"array";if(a instanceof window.Object)return c;var f=window.Object.prototype.toString.call(a);if("[object Window]"==f)return"object";if("[object Array]"==f||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==f||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==c&&"undefined"==typeof a.call)return"object";return c};_.E=function(a){return a!==_.p};_.ea=function(a){return"array"==(0,_.da)(a)};_.ga=function(a){var c=(0,_.da)(a);return"array"==c||"object"==c&&"number"==typeof a.length};_.ha=function(a){return"string"==typeof a};_.ia=function(a){return"function"==(0,_.da)(a)};_.ja=function(a){var c=typeof a;return"object"==c&&a!=_.s||"function"==c};_.ka=function(a,c,f){return a.call.apply(a.bind,arguments)};
_.la=function(a,c,f){a||(0,_.m)((0,window.Error)());if(2<arguments.length){var g=window.Array.prototype.slice.call(arguments,2);return function(){var f=window.Array.prototype.slice.call(arguments);window.Array.prototype.unshift.apply(f,g);return a.apply(c,f)}}return function(){return a.apply(c,arguments)}};_.G=function(a,c,f){_.G=window.Function.prototype.bind&&-1!=window.Function.prototype.bind.toString().indexOf("native code")?_.ka:_.la;return _.G.apply(_.s,arguments)};
_.ma=function(a,c){var f=window.Array.prototype.slice.call(arguments,1);return function(){var c=window.Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return a.apply(this,c)}};_._DumpException=function(a){(0,_.m)(a)};_.na=_.na||{};_.D=this;_.oa="closure_uid_"+window.Math.floor(2147483648*window.Math.random()).toString(36);_.pa=window.Date.now||function(){return+new window.Date}; window.Function.prototype.bind=window.Function.prototype.bind||function(a,c){if(1<arguments.length){var f=window.Array.prototype.slice.call(arguments,1);f.unshift(this,a);return _.G.apply(_.s,f)}return(0,_.G)(this,a)};
_.qa=window.gapi||{};_.sa=window.gadgets||{};_.H=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},client:{jsonpOverride:_.u},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.u},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:_.u},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/u/:session_index:/_/pages/badge"},":socialhost:":"https://plusone.google.com",card:{params:{s:"#",userid:"&"},url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton"},
plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator"},appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"chili.people.list":_.r,"pos.plusones.list":_.r,"pos.plusones.get":_.r,"chili.people.get":_.r,
"pos.plusones.insert":_.r,"chili.activities.list":_.r,"pos.plusones.delete":_.r,"chili.activities.get":_.r,"chili.activities.search":_.r,"pos.plusones.getSignupState":_.r},requestCache:{enabled:_.r},versions:{chili:"v1",pos:"v1"},rpc:"/rpc",root:"https://www.googleapis.com","root-1p":"https://clients6.google.com",sessionCache:{enabled:_.r},transport:{isProxyShared:_.r},xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:_.u}},drive_saver:{driveUrl:"https://drive.google.com"}});

window.___jsl=window.___jsl||{};(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"onload"},iframes:{":source:":"3p"}});
_.I=function(a,c,f){return a[c]=a[c]||f};_.va=function(a){return"function"===typeof a};_.wa=function(a){return(0,window.String)(a).replace(_.xa,"&amp;").replace(_.ya,"&lt;").replace(_.za,"&gt;").replace(_.Aa,"&quot;").replace(_.Ba,"&#39;")};_.L=function(){var a;if((a=window.Object.create)&&_.Ca.test(a))a=a(_.s);else{a={};for(var c in a)a[c]=_.p}return a};_.Da=function(a,c){return window.Object.prototype.hasOwnProperty.call(a,c)};_.Ea=function(a,c){a=a||{};for(var f in a)(0,_.Da)(a,f)&&(c[f]=a[f])};
_.Fa=function(a,c){a||(0,_.m)((0,window.Error)(c||""))};_.Ga=function(a,c,f){var g=(0,window.RegExp)("([#].*&|[#])"+c+"=([^&#]*)","g");c=(0,window.RegExp)("([?#].*&|[?#])"+c+"=([^&#]*)","g");if(a=a&&(g.exec(a)||c.exec(a)))try{f=(0,window.decodeURIComponent)(a[2])}catch(h){}return f};_.Ha=function(a){a=a.match(_.Ia);var c=(0,_.L)();c.xc=a[1];c.kb=a[3]?[a[3]]:[];c.Wf=a[5]?[a[5]]:[];return c};
_.Ja=function(a){a=a?a.split("&"):[];for(var c=[],f=0;f<a.length;f++){var g=a[f].split("=",2);c.push([(0,window.decodeURIComponent)(g[0]),(0,window.decodeURIComponent)(g[1])])}return c};_.Ka=function(a){return a.xc+(0<a.kb.length?"?"+a.kb.join("&"):"")+(0<a.Wf.length?"#"+a.Wf.join("&"):"")};_.La=function(a){var c=[];if(a)for(var f in a)(0,_.Da)(a,f)&&a[f]!=_.s&&c.push((0,window.encodeURIComponent)(f)+"="+(0,window.encodeURIComponent)(a[f]));return c};
_.Ma=function(a,c,f){a=(0,_.Ha)(a);a.kb.push.apply(a.kb,(0,_.La)(c));a.Wf.push.apply(a.Wf,(0,_.La)(f));return(0,_.Ka)(a)};_.Na=function(a,c){var f=a.createElement("div"),g=a.createElement("a");g.href=c;f.appendChild(g);f.innerHTML=f.innerHTML;c=(0,window.String)(f.firstChild.href);f.parentNode&&f.parentNode.removeChild(f);return c};_.Oa=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.Pa=function(a){return!_.Qa.dpo?(0,_.Ga)(a,"jsh",_.Qa.h):_.Qa.h};
_.Ra=function(a){return(0,_.Ga)(a,"_bsh",_.Qa.bsh)};_.Sa=function(){return(0,_.I)(_.Qa,"WI",(0,_.L)())};_.Ta=function(){return _.Qa.ssfn};_.Ua=function(){return _.Qa.onl};_.Va=function(a){_.Qa.onl=a};_.Wa=function(a){var c=window.___jsl=window.___jsl||{};c[a]=c[a]||[];return c[a]};_.Xa=function(a){var c=window.___jsl=window.___jsl||{};c.cfg=!a&&c.cfg||{};return c.cfg};_.Ya=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
_.Za=function(a,c){if(c)for(var f in c)c.hasOwnProperty(f)&&(a[f]&&c[f]&&"object"===typeof a[f]&&"object"===typeof c[f]&&!(0,_.Ya)(a[f])&&!(0,_.Ya)(c[f])?(0,_.Za)(a[f],c[f]):c[f]&&"object"===typeof c[f]?(a[f]=(0,_.Ya)(c[f])?[]:{},(0,_.Za)(a[f],c[f])):a[f]=c[f])};
_.$a=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);var c;try{c=window.JSON.parse(a)}catch(f){}if("object"===typeof c)return c;try{c=(new window.Function("return ("+a+"\n)"))()}catch(g){}if("object"===typeof c)return c;try{c=(new window.Function("return ({"+a+"\n})"))()}catch(h){}return"object"===typeof c?c:{}}};
_.ab=function(a){(0,_.Xa)(_.r);var c=window.___gcfg,f=(0,_.Wa)("cu");if(c&&c!==window.___gu){var g={};(0,_.Za)(g,c);f.push(g);window.___gu=c}var c=(0,_.Wa)("cu"),h=window.document.scripts||window.document.getElementsByTagName("script")||[],g=[],l=[];l.push.apply(l,(0,_.I)(_.Qa,"us",[]));for(var n=0;n<h.length;++n)for(var q=h[n],t=0;t<l.length;++t)q.src&&0==q.src.indexOf(l[t])&&g.push(q);0==g.length&&(0<h.length&&h[h.length-1].src)&&g.push(h[h.length-1]);for(h=0;h<g.length;++h)g[h].getAttribute("gapi_processed")||
(g[h].setAttribute("gapi_processed",_.r),(l=g[h])?(n=l.nodeType,l=3==n||4==n?l.nodeValue:l.textContent||l.innerText||l.innerHTML||""):l=_.p,(l=(0,_.$a)(l))&&c.push(l));a&&(g={},(0,_.Za)(g,a),f.push(g));g=(0,_.Wa)("cd");a=0;for(c=g.length;a<c;++a)(0,_.Za)((0,_.Xa)(),g[a]);g=(0,_.Wa)("ci");a=0;for(c=g.length;a<c;++a)(0,_.Za)((0,_.Xa)(),g[a]);a=0;for(c=f.length;a<c;++a)(0,_.Za)((0,_.Xa)(),f[a])};
_.N=function(a,c){if(!a)return(0,_.Xa)();for(var f=a.split("/"),g=(0,_.Xa)(),h=0,l=f.length;g&&"object"===typeof g&&h<l;++h)g=g[f[h]];return h===f.length&&g!==_.p?g:c};_.bb=function(a,c){var f=a;if("string"===typeof a){for(var g=f={},h=a.split("/"),l=0,n=h.length;l<n-1;++l)var q={},g=g[h[l]]=q;g[h[l]]=c}(0,_.ab)(f)};_.cb=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),(0,_.I)(_.Qa,"ci",[]).push(a),window.__GOOGLEAPIS=_.p)}; _.O=function(a,c){c="function"==typeof _.db&&(0,_.db)(a,c)||c;(0,_.C)(a,c,_.p)};
_.eb=window;_.fb=window.document;_.Ca=/\[native code\]/;_.xa=/&/g;_.ya=/</g;_.za=/>/g;_.Aa=/"/g;_.Ba=/'/g;_.gb=(0,_.I)(_.eb,"gapi",{});_.Ia=/^([^?#]*)(\?([^#]*))?(\#(.*))?$/;_.Qa=(0,_.I)(_.eb,"___jsl",(0,_.L)());(0,_.I)(_.Qa,"I",0);(0,_.I)(_.Qa,"hel",10);_.cb&&(0,_.cb)();(0,_.ab)();(0,_.O)("gapi.config.get",_.N);(0,_.O)("gapi.config.update",_.bb);


_.mb={go:{},J:{}};_.nb={go:{},J:{}};


_.Q=_.Q||{};
_.Q=_.Q||{};_.Q.Fg=function(a,c,f){for(var g=[],h=2,l=arguments.length;h<l;++h)g.push(arguments[h]);return function(){for(var f=g.slice(),h=0,l=arguments.length;h<l;++h)f.push(arguments[h]);return c.apply(a,f)}};_.Q.of=function(a){var c,f,g={};for(c=0;f=a[c];++c)g[f]=f;return g};

_.vb=function(a,c){return window.String.fromCharCode(c)};_.Q=_.Q||{};_.wb={"0":_.u,10:_.r,13:_.r,34:_.r,39:_.r,60:_.r,62:_.r,92:_.r,8232:_.r,8233:_.r,65282:_.r,65287:_.r,65308:_.r,65310:_.r,65340:_.r};_.Q.escape=function(a,c){if(a){if("string"===typeof a)return _.Q.Rf(a);if("array"===typeof a)for(var f=0,g=a.length;f<g;++f)a[f]=_.Q.escape(a[f]);else if("object"===typeof a&&c){f={};for(g in a)a.hasOwnProperty(g)&&(f[_.Q.Rf(g)]=_.Q.escape(a[g],_.r));return f}}return a}; _.Q.Rf=function(a){if(!a)return a;for(var c=[],f,g,h=0,l=a.length;h<l;++h)f=a.charCodeAt(h),g=_.wb[f],g===_.r?c.push("&#",f,";"):g!==_.u&&c.push(a.charAt(h));return c.join("")};_.Q.Cv=function(a){return!a?a:a.replace(/&#([0-9]+);/g,_.vb)};

_.zb=_.zb||{};_.zb.Zp=function(){var a=0,c=0;window.self.innerHeight?(a=window.self.innerWidth,c=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,c=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,c=window.document.body.clientHeight);return{width:a,height:c}};

_.Ab=function(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(window.RegExp.$1,10)};_.zb=_.zb||{};
_.zb.Sh=function(){var a=_.zb.Zp().height,c=window.document.body,f=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&f.scrollHeight)return f.scrollHeight!==a?f.scrollHeight:f.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){a=0;for(c=[window.document.body];0<c.length;){var g=c.shift(),f=g.childNodes;if("undefined"!==typeof g.style){var h=g.style.overflowY;h||(h=(h=window.document.defaultView.getComputedStyle(g,_.s))?h.overflowY:_.s);if("visible"!=h&&
"inherit"!=h&&(h=g.style.height,h||(h=(h=window.document.defaultView.getComputedStyle(g,_.s))?h.height:""),0<h.length&&"auto"!=h))continue}for(g=0;g<f.length;g++){h=f[g];if("undefined"!==typeof h.offsetTop&&"undefined"!==typeof h.offsetHeight)var l=h.offsetTop+h.offsetHeight+(0,_.Ab)(h,"margin-bottom"),a=window.Math.max(a,l);c.push(h)}}return a+(0,_.Ab)(window.document.body,"border-bottom")+(0,_.Ab)(window.document.body,"margin-bottom")+(0,_.Ab)(window.document.body,"padding-bottom")}if(c&&f)return g= f.scrollHeight,h=f.offsetHeight,f.clientHeight!==h&&(g=c.scrollHeight,h=c.offsetHeight),g>a?g>h?g:h:g<h?g:h};

_.Vc=window.gapi&&window.gapi.util||{};
_.Wc=_.Vc=_.Vc||{};_.Xc={Fj:"bsh",Ij:"h"};window.___jsl=window.___jsl||{};_.Wc.ph={b:function(){return window.___jsl[_.Xc.Fj]},sk:function(){return window.___jsl[_.Xc.Ij]},gj:function(a){window.___jsl[_.Xc.Fj]=a},hs:function(a){window.___jsl[_.Xc.Ij]=a}};

if(window.JSON&&window.JSON.parse&&window.JSON.stringify){_.ob=function(a){return this[a]};_.pb=/___$/;_.P={parse:function(a){try{return window.JSON.parse(a)}catch(c){return _.u}},stringify:function(a){function c(a){return f.call(this,a,_.ob)}var f=window.JSON.stringify,g=window.Array.prototype.toJSON&&'"[{\\"x\\": 1}]"'===f([{x:1}])?c:f;try{return g(a,function(a,c){return!_.pb.test(a)?c:_.p})}catch(h){return _.s}}}};
if(!window.JSON||!window.JSON.parse||!window.JSON.stringify)_.P=function(){function a(a){return 10>a?"0"+a:a}function c(a){var h,l,n;h=/[\"\\\x00-\x1f\x7f-\x9f]/g;switch(typeof a){case "string":return h.test(a)?'"'+a.replace(h,function(a){var c=f[a];if(c)return c;c=a.charCodeAt();return"\\u00"+window.Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+a+'"';case "number":return(0,window.isFinite)(a)?(0,window.String)(a):"null";case "boolean":case "null":return(0,window.String)(a);case "object":if(!a)return"null";
h=[];if("number"===typeof a.length&&!a.propertyIsEnumerable("length")){n=a.length;for(l=0;l<n;l+=1)h.push(c(a[l])||"null");return"["+h.join(",")+"]"}for(l in a)!/___$/.test(l)&&a.hasOwnProperty(l)&&"string"===typeof l&&(n=c(a[l]))&&h.push(c(l)+":"+n);return"{"+h.join(",")+"}"}return""}window.Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",a(this.getUTCMonth()+1),"-",a(this.getUTCDate()),"T",a(this.getUTCHours()),":",a(this.getUTCMinutes()),":",a(this.getUTCSeconds()),"Z"].join("")};
var f={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};return{stringify:c,parse:function(a){return/^[\],:{}\s]*$/.test(a.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))?eval("("+a+")"):_.u}}}();
_.P.lk=function(a){var c={};if(a===_.s||a===_.p)return c;for(var f in a)if(a.hasOwnProperty(f)){var g=a[f];_.s===g||_.p===g||(c[f]="string"===typeof g?g:_.P.stringify(g))}return c};(0,_.O)("gadgets.json.flatten",_.P.lk);(0,_.O)("gadgets.json.parse",_.P.parse);(0,_.O)("gadgets.json.stringify",_.P.stringify);(0,_.O)("gadgets.json.flatten",_.P.lk);(0,_.O)("gadgets.json.parse",_.P.parse);(0,_.O)("gadgets.json.stringify",_.P.stringify);

_.Q=_.Q||{};_.Bb=[];_.Q.sv=function(a){_.Bb.push(a)};_.Q.xv=function(){for(var a=0,c=_.Bb.length;a<c;++a)_.Bb[a]()};
_.xb=function(a){for(var c=0;c<this.length;c++)if(this[c]===a)return c;return-1};_.Q=_.Q||{};_.yb=_.s;
_.Q.oa=function(a){var c="undefined"===typeof a;if(_.yb!==_.s&&c)return _.yb;var f={};a=a||window.document.location.href;var g=a.indexOf("?"),h=a.indexOf("#");a=(-1===h?a.substr(g+1):[a.substr(g+1,h-g-1),"&",a.substr(h+1)].join("")).split("&");for(var g=window.decodeURIComponent?window.decodeURIComponent:window.unescape,h=0,l=a.length;h<l;++h){var n=a[h].indexOf("=");if(-1!==n){var q=a[h].substring(0,n),n=a[h].substring(n+1),n=n.replace(/\+/g," ");try{f[q]=g(n)}catch(t){}}}c&&(_.yb=f);return f};_.Q.oa();
(0,_.O)("gadgets.util.getUrlParameters",_.Q.oa);
_.Db=window.gadgets&&window.gadgets.config&&window.gadgets.config.get;_.Db&&(0,_.bb)((0,_.Db)());_.Cb={O:function(a,c,f){f&&f((0,_.N)())},get:function(a){return(0,_.N)(a)},update:function(a,c){c&&(0,_.m)("Config replacement is not supported");(0,_.bb)(a)},fa:(0,_.v)()};
(0,_.O)("gadgets.config.register",_.Cb.O);(0,_.O)("gadgets.config.get",_.Cb.get);(0,_.O)("gadgets.config.init",_.Cb.fa);(0,_.O)("gadgets.config.update",_.Cb.update);
_.Eb=_.Eb||{};_.Eb.jm=_.s;_.Eb.Fl=_.s;_.Eb.sg=_.s;_.Eb.frameElement=_.s;_.Eb=_.Eb||{};
if(!_.Eb.Cj){_.Hb=function(a){var c=_.P.parse(a.data);if(c&&c.f){var f=_.R.ae(c.f);(!_.Fb||!("undefined"!==typeof a.origin?a.origin!==f:a.domain!==/^.+:\/\/([^:]+).*/.exec(f)[1]))&&(0,_.Gb)(c,a.origin)}};_.Fb=_.r;_.Eb.Cj={qk:(0,_.ca)("wpm"),b:(0,_.ca)(_.r),fa:function(a,c){_.Cb.O("rpc",_.s,function(a){if("true"===(0,window.String)((a&&a.rpc||{}).disableForceSecure))_.Fb=_.u});_.Gb=a;_.Ib=c;"undefined"!=typeof window.addEventListener?window.addEventListener("message",_.Hb,_.u):"undefined"!=typeof window.attachEvent&&
window.attachEvent("onmessage",_.Hb);window.___jsl=window.___jsl||{};var f=window.___jsl;f.RPMQ=f.RPMQ||[];f.RPMQ.push(_.Hb);(0,_.Ib)("..",_.r);return _.r},bd:function(a){(0,_.Ib)(a,_.r);return _.r},call:function(a,c,f){var g=_.R.ae(a),h=_.R.Qj(a);g?window.setTimeout(function(){h.postMessage(_.P.stringify(f),g)},0):".."!=a&&(0,_.ua)("No relay set (used as window.postMessage targetOrigin), cannot send cross-domain message");return _.r}}};
_.Eb=_.Eb||{};
if(!_.Eb.Vf){_.Jb=_.Eb;_.Mb=function(a,c){function f(){a.apply({},arguments)}_.Kb[c]=_.Kb[c]||f;return _.Lb+"."+c};_.Tb=function(){if(_.Nb===_.s&&window.document.body&&_.Ob){var a=_.Ob+"?cb="+window.Math.random()+"&origin="+_.Pb+"&jsl=1",c=window.document.createElement("div");c.style.height="1px";c.style.width="1px";a='<object height="1" width="1" id="'+_.Qb+'" type="application/x-shockwave-flash"><param name="allowScriptAccess" value="always"></param><param name="movie" value="'+a+'"></param><embed type="application/x-shockwave-flash" allowScriptAccess="always" src="'+
a+'" height="1" width="1"></embed></object>';window.document.body.appendChild(c);c.innerHTML=a;_.Nb=c.firstChild}++_.Rb;_.Sb!==_.s&&(_.Nb!==_.s||50<=_.Rb)?window.clearTimeout(_.Sb):_.Sb=window.setTimeout(_.Tb,100)};_.Yb=function(){_.Ub[".."]||((0,_.Vb)(".."),_.Wb++,50<=_.Wb&&_.Xb!==_.s?(window.clearTimeout(_.Xb),_.Xb=_.s):_.Xb=window.setTimeout(_.Yb,100))};_.bc=function(){if(_.Nb!==_.s&&_.Nb.setup)for(;0<_.Zb.length;){var a=_.Zb.shift(),c=a.Cs;_.Nb.setup(a.ve,".."===c?_.R.fh:c,".."===c?"INNER":"OUTER")}_.Sb!==
_.s&&window.clearTimeout(_.Sb);_.Sb=_.s};_.cc=function(){!_.Ub[".."]&&_.Xb===_.s&&(_.Xb=window.setTimeout(_.Yb,100))};_.dc=function(a,c,f){c=_.R.ae(a);var g=_.R.Xd(a);_.Nb["sendMessage_"+(".."===a?_.R.fh:a)+"_"+g+"_"+(".."===a?"INNER":"OUTER")].call(_.Nb,_.P.stringify(f),c);return _.r};_.gc=function(a,c){var f=_.P.parse(a),g=f._scr;g?((0,_.ec)(g,_.r),_.Ub[g]=_.r,".."!==g&&(0,_.Vb)(g,_.r)):window.setTimeout(function(){(0,_.fc)(f,c)},0)};_.Vb=function(a,c){var f=_.R.fh,g={};g._scr=c?"..":f;g._pnt=f;
(0,_.dc)(a,f,g)};_.Qb="___xpcswf";_.Ob=_.s;_.hc=_.u;_.fc=_.s;_.ec=_.s;_.Nb=_.s;_.Zb=[];_.Sb=_.s;_.Rb=0;_.Wb=0;_.Xb=_.s;_.Ub={};_.Pb=window.location.protocol+"//"+window.location.host;window.___jsl=window.___jsl||{};_.ic=window.___jsl._fm={};_.Lb="___jsl._fm";_.Kb=_.ic;_.Cb.O("rpc",_.s,function(a){_.hc&&(_.Ob=a&&a.rpc&&a.rpc.commSwf||"//xpc.googleusercontent.com/gadgets/xpc.swf")});(0,_.Mb)(_.bc,"ready");(0,_.Mb)(_.cc,"setupDone");(0,_.Mb)(_.gc,"receiveMessage");_.Jb.Vf={qk:(0,_.ca)("flash"),b:(0,_.ca)(_.r), fa:function(a,c){_.fc=a;_.ec=c;return _.hc=_.r},bd:function(a,c){_.Zb.push({ve:c,Cs:a});_.Nb===_.s&&_.Sb===_.s&&(_.Sb=window.setTimeout(_.Tb,100));return _.r},call:_.dc,zo:_.gc,d:_.bc,i:_.cc}};
if(!window.gadgets||!window.gadgets.rpc){_.qc=function(a,c){if(!_.jc[a]){var f=_.kc;c||(f=_.lc);_.jc[a]=f;for(var g=_.mc[a]||[],h=0;h<g.length;++h){var l=g[h];l.t=_.nc[a];f.call(a,l.f,l)}_.mc[a]=[]}};_.vc=function(a,c,f,g,h){function l(){_.rc=_.r}if(!_.nc[c]||_.nc[c]!==f)(0,_.ua)("Invalid gadgets.rpc token. "+_.nc[c]+" vs "+f),(0,_.sc)(c,2);h.onunload=function(){_.tc[c]&&!_.rc&&((0,_.sc)(c,1),_.R.ej(c))};_.uc||("undefined"!=typeof window.addEventListener?window.addEventListener("unload",l,_.u):"undefined"!=
typeof window.attachEvent&&window.attachEvent("onunload",l),_.uc=_.r);g=_.P.parse((0,window.decodeURIComponent)(g))};_.yc=function(a,c){if(a&&"string"===typeof a.s&&"string"===typeof a.f&&a.a instanceof window.Array)if(_.nc[a.f]&&_.nc[a.f]!==a.t&&((0,_.ua)("Invalid gadgets.rpc token. "+_.nc[a.f]+" vs "+a.t),(0,_.sc)(a.f,2)),"__ack"===a.s)window.setTimeout(function(){(0,_.qc)(a.f,_.r)},0);else{a.c&&(a.callback=function(c){_.R.call(a.f,(a.g?"legacy__":"")+"__cb",_.s,a.c,c)});if(c){var f=(0,_.wc)(c);
a.origin=c;var g=a.r;if(!g||(0,_.wc)(g)!=f)g=c;a.referer=g}f=(_.xc[a.s]||_.xc[""]).apply(a,a.a);a.c&&"undefined"!==typeof f&&_.R.call(a.f,"__cb",_.s,a.c,f)}};_.wc=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);-1==a.indexOf("://")&&(a=window.location.protocol+"//"+a);var c=a.substring(a.indexOf("://")+3),f=c.indexOf("/");-1!=f&&(c=c.substring(0,f));a=a.substring(0,a.indexOf("://"));var f="",g=c.indexOf(":");if(-1!=g){var h=
c.substring(g+1),c=c.substring(0,g);if("http"===a&&"80"!==h||"https"===a&&"443"!==h)f=":"+h}return a+"://"+c+f};_.zc=function(a){if("/"==a.charAt(0)){var c=a.indexOf("|");return{id:0<c?a.substring(1,c):a.substring(1),origin:0<c?a.substring(c+1):_.s}}return _.s};_.Ac=function(a){if("undefined"===typeof a||".."===a)return window.parent;var c=(0,_.zc)(a);if(c)return window.top.frames[c.id];a=(0,window.String)(a);return(c=window.frames[a])?c:(c=window.document.getElementById(a))&&c.contentWindow?c.contentWindow:
_.s};_.Bc=function(a,c){if(_.tc[a]!==_.r){"undefined"===typeof _.tc[a]&&(_.tc[a]=0);var f=(0,_.Ac)(a);(".."===a||f!=_.s)&&_.kc.bd(a,c)===_.r?_.tc[a]=_.r:_.tc[a]!==_.r&&10>_.tc[a]++?window.setTimeout(function(){(0,_.Bc)(a,c)},500):(_.jc[a]=_.lc,_.tc[a]=_.r)}};_.Dc=function(a){(a=_.Cc[a])&&"/"===a.substring(0,1)&&(a="/"===a.substring(1,2)?window.document.location.protocol+a:window.document.location.protocol+"//"+window.document.location.host+a);return a};_.Gc=function(a,c,f){c&&!/http(s)?:\/\/.+/.test(c)&&
(0==c.indexOf("//")?c=window.location.protocol+c:"/"==c.charAt(0)?c=window.location.protocol+"//"+window.location.host+c:-1==c.indexOf("://")&&(c=window.location.protocol+"//"+c));_.Cc[a]=c;"undefined"!==typeof f&&(_.Fc[a]=!!f)};_.Hc=function(a,c){c=c||"";_.nc[a]=(0,window.String)(c);(0,_.Bc)(a,c)};_.Kc=function(a){a=(a.passReferrer||"").split(":",2);_.Ic=a[0]||"none";_.Jc=a[1]||"origin"};_.Lc=function(a){"true"===(0,window.String)(a.useLegacyProtocol)&&(_.kc=_.Eb.sg||_.lc,_.kc.fa(_.yc,_.qc))};_.Nc=
function(a,c,f){if(".."===a){var g=f||_.Mc.rpctoken||_.Mc.ifpctok||"";a=function(a){a=a&&a.rpc||{};(0,_.Kc)(a);var f=a.parentRelayUrl||"",f=(0,_.wc)(_.Mc.parent||c)+f;(0,_.Gc)("..",f,"true"===(0,window.String)(a.useLegacyProtocol));(0,_.Lc)(a);(0,_.Hc)("..",g)};!_.Mc.parent&&c?a({}):_.Cb.O("rpc",_.s,a)}else a:{var h=_.s;if("/"!=a.charAt(0)){if(!_.Q)break a;(h=window.document.getElementById(a))||(0,_.m)((0,window.Error)("h`"+a))}var h=h&&h.src,l=c||_.R.la(h);(0,_.Gc)(a,l);h=_.Q.oa(h);(0,_.Hc)(a,f||
h.rpctoken)}};_.xc={};_.Cc={};_.Fc={};_.nc={};_.Oc=0;_.Pc={};_.tc={};_.Mc={};_.jc={};_.mc={};_.Ic=_.s;_.Jc=_.s;_.Qc=window.top!==window.self;_.Rc=window.name;_.sc=(0,_.v)();_.Sc=window.console;_.Tc=_.Sc&&_.Sc.log&&function(a){_.Sc.log(a)}||(0,_.v)();_.Uc=function(a){return function(){(0,_.Tc)(a+": call ignored")}};_.lc={getCode:(0,_.ca)("noop"),isParentVerifiable:(0,_.ca)(_.r),init:(0,_.Uc)("init"),setup:(0,_.Uc)("setup"),call:(0,_.Uc)("call")};_.Q&&(_.Mc=_.Q.oa());_.rc=_.u;_.uc=_.u;_.kc=function(){if("flash"==
_.Mc.rpctx)return _.Eb.Vf;if("rmr"==_.Mc.rpctx)return _.Eb.jm;var a="function"===typeof window.postMessage?_.Eb.Cj:"object"===typeof window.postMessage?_.Eb.Cj:window.ActiveXObject?_.Eb.Vf?_.Eb.Vf:_.Eb.Fl?_.Eb.Fl:_.Eb.sg:0<window.navigator.userAgent.indexOf("WebKit")?_.Eb.jm:"Gecko"===window.navigator.product?_.Eb.frameElement:_.Eb.sg;a||(a=_.lc);return a}();_.xc[""]=function(){(0,_.Tc)("Unknown RPC service: "+this.s)};_.xc.__cb=function(a,c){var f=_.Pc[a];f&&(delete _.Pc[a],f.call(this,c))};_.R=
{Ga:function(a){"function"===typeof a.Sr&&(_.sc=a.Sr)},O:function(a,c){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("i"));""===a&&(0,_.m)((0,window.Error)("j"));_.xc[a]=c},Wb:function(a){("__cb"===a||"__ack"===a)&&(0,_.m)((0,window.Error)("k"));""===a&&(0,_.m)((0,window.Error)("l"));delete _.xc[a]},$l:function(a){_.xc[""]=a},Km:function(){delete _.xc[""]},ok:(0,_.v)(),call:function(a,c,f,g){a=a||"..";var h="..";".."===a?h=_.Rc:"/"==a.charAt(0)&&(h=_.R.la(window.location.href),h="/"+_.Rc+(h?
"|"+h:""));++_.Oc;f&&(_.Pc[_.Oc]=f);var l={s:c,f:h,c:f?_.Oc:0,a:window.Array.prototype.slice.call(arguments,3),t:_.nc[a],l:!!_.Fc[a]},n;a:if("bidir"===_.Ic||"c2p"===_.Ic&&".."===a||"p2c"===_.Ic&&".."!==a){n=window.location.href;var q="?";if("query"===_.Jc)q="#";else if("hash"===_.Jc)break a;q=n.lastIndexOf(q);q=-1===q?n.length:q;n=n.substring(0,q)}else n=_.s;n&&(l.r=n);".."!==a&&(0,_.zc)(a)==_.s&&!window.document.getElementById(a)||(n=_.jc[a],!n&&(0,_.zc)(a)!==_.s&&(n=_.kc),0===c.indexOf("legacy__")&&
(n=_.kc,l.s=c.substring(8),l.c=l.c?l.c:_.Oc),l.g=_.r,l.r=h,n?(_.Fc[a]&&(n=_.Eb.sg),n.call(a,h,l)===_.u&&(_.jc[a]=_.lc,_.kc.call(a,h,l))):_.mc[a]?_.mc[a].push(l):_.mc[a]=[l])},vk:_.Dc,Wg:_.Gc,Vg:_.Hc,tf:_.Nc,Xd:function(a){return _.nc[a]},ej:function(a){delete _.Cc[a];delete _.Fc[a];delete _.nc[a];delete _.tc[a];delete _.jc[a]},uk:function(){return _.kc.qk()},Yl:function(a,c){4<a.length?_.kc.zo(a,_.yc):_.vc.apply(_.s,a.concat(c))},Zl:function(a){a.a=window.Array.prototype.slice.call(a.a);window.setTimeout(function(){(0,_.yc)(a)},
0)},la:_.wc,ae:function(a){var c=_.s,c=(0,_.Dc)(a);c||(c=(c=(0,_.zc)(a))?c.origin:".."==a?_.Mc.parent:window.document.getElementById(a).src);return(0,_.wc)(c)},fa:function(){_.kc.fa(_.yc,_.qc)===_.u&&(_.kc=_.lc);_.Qc?(0,_.Nc)(".."):_.Cb.O("rpc",_.s,function(a){a=a.rpc||{};(0,_.Kc)(a);(0,_.Lc)(a)})},Qj:_.Ac,yo:_.zc,b:"__ack",fh:_.Rc||"..",j:0,i:1,d:2};_.R.fa()}else if("undefined"==typeof _.R||!_.R)_.R=window.gadgets.rpc,_.R.Ga=_.R.config,_.R.O=_.R.register,_.R.Wb=_.R.unregister,_.R.$l=_.R.registerDefault,
_.R.Km=_.R.unregisterDefault,_.R.ok=_.R.forceParentVerifiable,_.R.call=_.R.call,_.R.vk=_.R.getRelayUrl,_.R.Wg=_.R.setRelayUrl,_.R.Vg=_.R.setAuthToken,_.R.tf=_.R.setupReceiver,_.R.Xd=_.R.getAuthToken,_.R.ej=_.R.removeReceiver,_.R.uk=_.R.getRelayChannel,_.R.Yl=_.R.receive,_.R.Zl=_.R.receiveSameDomain,_.R.la=_.R.getOrigin,_.R.ae=_.R.getTargetOrigin,_.R.Qj=_.R._getTargetWin,_.R.yo=_.R._parseSiblingId;
(0,_.O)("gadgets.rpc.config",_.R.Ga);(0,_.O)("gadgets.rpc.register",_.R.O);(0,_.O)("gadgets.rpc.unregister",_.R.Wb);(0,_.O)("gadgets.rpc.registerDefault",_.R.$l);(0,_.O)("gadgets.rpc.unregisterDefault",_.R.Km);(0,_.O)("gadgets.rpc.forceParentVerifiable",_.R.ok);(0,_.O)("gadgets.rpc.call",_.R.call);(0,_.O)("gadgets.rpc.getRelayUrl",_.R.vk);(0,_.O)("gadgets.rpc.setRelayUrl",_.R.Wg);(0,_.O)("gadgets.rpc.setAuthToken",_.R.Vg);(0,_.O)("gadgets.rpc.setupReceiver",_.R.tf);
(0,_.O)("gadgets.rpc.getAuthToken",_.R.Xd);(0,_.O)("gadgets.rpc.removeReceiver",_.R.ej);(0,_.O)("gadgets.rpc.getRelayChannel",_.R.uk);(0,_.O)("gadgets.rpc.receive",_.R.Yl);(0,_.O)("gadgets.rpc.receiveSameDomain",_.R.Zl);(0,_.O)("gadgets.rpc.getOrigin",_.R.la);(0,_.O)("gadgets.rpc.getTargetOrigin",_.R.ae);

_.qb=function(a,c){if(!(a<_.rb)&&_._console$$inline_313)if(2===a&&_._console$$inline_313.warn)_._console$$inline_313.warn(c);else if(3===a&&_._console$$inline_313.error)try{_._console$$inline_313.error(c)}catch(f){}else _._console$$inline_313.log&&_._console$$inline_313.log(c)};_.sb=function(a){(0,_.qb)(1,a)};_.tb=function(a){(0,_.qb)(2,a)};_.ua=function(a){(0,_.qb)(3,a)};_.sb.INFO=1;_.sb.WARNING=2;_.sb.NONE=4;_.rb=1; _._console$$inline_313=window.console?window.console:window.opera?window.opera.postError:_.p;

_.Q=_.Q||{};_.Q.Fe=function(a,c,f,g){"undefined"!=typeof a.addEventListener?a.addEventListener(c,f,g):"undefined"!=typeof a.attachEvent?a.attachEvent("on"+c,f):(0,_.tb)("cannot attachBrowserEvent: "+c)};_.Q.Dr=function(a,c,f,g){a.removeEventListener?a.removeEventListener(c,f,g):a.detachEvent?a.detachEvent("on"+c,f):(0,_.tb)("cannot removeBrowserEvent: "+c)};

_.Zc=function(){function a(){h[0]=1732584193;h[1]=4023233417;h[2]=2562383102;h[3]=271733878;h[4]=3285377520;x=w=0}function c(a){for(var c=n,f=0;64>f;f+=4)c[f/4]=a[f]<<24|a[f+1]<<16|a[f+2]<<8|a[f+3];for(f=16;80>f;f++)c[f]=((c[f-3]^c[f-8]^c[f-14]^c[f-16])<<1|(c[f-3]^c[f-8]^c[f-14]^c[f-16])>>>31)&4294967295;a=h[0];for(var g=h[1],l=h[2],q=h[3],t=h[4],w,x,f=0;80>f;f++)40>f?20>f?(w=q^g&(l^q),x=1518500249):(w=g^l^q,x=1859775393):60>f?(w=g&l|q&(g|l),x=2400959708):(w=g^l^q,x=3395469782),w=((a<<5|a>>>27)&4294967295)+
w+t+x+c[f]&4294967295,t=q,q=l,l=(g<<30|g>>>2)&4294967295,g=a,a=w;h[0]=h[0]+a&4294967295;h[1]=h[1]+g&4294967295;h[2]=h[2]+l&4294967295;h[3]=h[3]+q&4294967295;h[4]=h[4]+t&4294967295}function f(a,f){if("string"===typeof a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var g=[],h=0,n=a.length;h<n;++h)g.push(a.charCodeAt(h));a=g}f||(f=a.length);g=0;if(0==w)for(;g+64<f;)c(a.slice(g,g+64)),g+=64,x+=64;for(;g<f;)if(l[w++]=a[g++],x++,64==w){w=0;for(c(l);g+64<f;)c(a.slice(g,g+64)),g+=64,x+=64}}
function g(){var a=[],g=8*x;56>w?f(q,56-w):f(q,64-(w-56));for(var n=63;56<=n;n--)l[n]=g&255,g>>>=8;c(l);for(n=g=0;5>n;n++)for(var t=24;0<=t;t-=8)a[g++]=h[n]>>t&255;return a}for(var h=[],l=[],n=[],q=[128],t=1;64>t;++t)q[t]=0;var w,x;a();return{reset:a,update:f,$u:g,Pf:function(){for(var a=g(),c="",f=0;f<a.length;f++)c+="0123456789ABCDEF".charAt(window.Math.floor(a[f]/16))+"0123456789ABCDEF".charAt(a[f]%16);return c}}};

_.$c=function(a){if("complete"===_.fb.readyState)a();else{var c=_.u,f=function(){if(!c)return c=_.r,a.apply(this,arguments)};_.eb.addEventListener?(_.eb.addEventListener("load",f,_.u),_.eb.addEventListener("DOMContentLoaded",f,_.u)):_.eb.attachEvent&&(_.eb.attachEvent("onreadystatechange",function(){"complete"===_.fb.readyState&&f.apply(this,arguments)}),_.eb.attachEvent("onload",f))}};_.bd=function(a){var c=(0,_.Zc)();c.update(a);return c.Pf()};_.cd=window.crypto;
if(_.cd&&"function"==typeof _.cd.getRandomValues)_.ad=function(){var a=new window.Uint32Array(1);_.cd.getRandomValues(a);return(0,window.Number)("0."+a[0])};else{_.dd=(0,_.N)("random/maxObserveMousemove");_.dd==_.s&&(_.dd=-1);_.ed=0;_.fd=window.Math.random();_.gd=1;_.hd=1E6*(window.screen.width*window.screen.width+window.screen.height);_.id=function(a){a=a||window.event;var c=a.screenX+a.clientX<<16,c=c+(a.screenY+a.clientY),c=c*((new window.Date).getTime()%1E6);_.gd=_.gd*c%_.hd;0<_.dd&&++_.ed==_.dd&&
_.Q.Dr(window,"mousemove",_.id,_.u)};0!=_.dd&&_.Q.Fe(window,"mousemove",_.id,_.u);_.jd=(0,_.bd)(window.document.cookie+"|"+window.document.location+"|"+(new window.Date).getTime()+"|"+_.fd);_.ad=function(){var a=_.gd,a=a+(0,window.parseInt)(_.jd.substr(0,20),16);_.jd=(0,_.bd)(_.jd);return a/(_.hd+window.Math.pow(16,20))}};
(0,_.O)("shindig.random",_.ad);
_.Yc=window.iframer=window.iframer||{};_.S=window.iframes=window.iframes||{};
_.S.Mo=function(a,c,f){var g=window.Array.prototype.slice.call(arguments);_.S.tk(function(a){a.sameOrigin&&(g.unshift("/"+a.claimedOpenerId+"|"+window.location.protocol+"//"+window.location.host),_.R.call.apply(_.R,g))})};_.S.Ar=function(a,c){_.R.O(a,c)};

_.kd=function(a){var c=(0,_.N)("googleapis.config/sessionIndex");c==_.s&&(c=window.__X_GOOG_AUTHUSER);if(c==_.s){var f=window.google;f&&(c=f.authuser)}c==_.s&&(a==_.s&&(a=window.location.href),c=a?(0,_.Ga)(a,"authuser")||_.s:_.s);return c==_.s?_.s:(0,window.String)(c)};
_.ld=function(a,c,f){a=(0,window.String)(a);if(((0,_.Ga)(a,"authuser")||_.s)!=_.s||((0,_.Ga)(a,"hd")||_.s)!=_.s)return a;c=(0,_.kd)(c);if(f){var g=a,h=g.match(/^((https?:)?\/\/[^\/?#]*)?(\/[^\/?#]+)\/[0-9]+([\/][^?#]*)([?#].*)?$/);if(h&&h[0]){var l=h[1],n=h[4],q=h[5];h[3]=="/"+f&&(g=(l||"")+(n||"/")+(q||""))}if((h=g.match(/^(((https?:)?\/\/[^\/?#]*)([\/][^?#]*)?|([\/][^?#]*))([?#].*)?$/))&&h[0])return l=h[2],a=h[4]||h[5],q=h[6],c!=_.s&&(g=(l||"")+"/"+f+"/"+(0,window.encodeURIComponent)(c)+(a||"/")+
(q||"")),g}f=c==_.s?(0,window.encodeURIComponent)("authuser")+"=0":c.match(/^([-a-z0-9]+[.])+[-a-z0-9]+$/)?[(0,window.encodeURIComponent)("authuser")+"=",(0,window.encodeURIComponent)((0,window.String)(c)),"&"+(0,window.encodeURIComponent)("hd")+"=",(0,window.encodeURIComponent)(c)].join(""):["authuser=",(0,window.encodeURIComponent)(c)].join("");a=a.split("#");c=a[0].indexOf("?");0>c?a[0]=[a[0],"?",f].join(""):(g=[a[0]],c<a[0].length-1&&g.push("&"),g.push(f),a[0]=g.join(""));return g=a.join("#")};
_.md=_.ld;
_.nd=function(){var a=(0,_.Ua)();if(!a){a=(0,_.L)();(0,_.Va)(a);var c=(0,_.L)();a.e=function(a){var g=c[a];g&&(delete c[a],g())};a.a=function(a,g){c[a]=g};a.r=function(a){delete c[a]}}return a};
_.od=function(a,c,f,g,h){var l,n;var q=f.onload;(0,_.va)(q)?((0,_.nd)().a(g,q),n=q):n=_.s;n?((0,_.Fa)(/^\w+$/.test(g),"Unsupported id - "+g),(0,_.nd)(),q='onload="window.___jsl.onl.e(&#34;'+g+'&#34;)"'):q="";try{l=a.createElement('<iframe frameborder="'+(0,_.wa)(f.frameborder)+'" scrolling="'+(0,_.wa)(f.scrolling)+'" '+q+' name="'+(0,_.wa)(f.name)+'"/>')}catch(t){l=a.createElement("iframe"),n&&(l.onload=function(){l.onload=_.s;n.call(this)},(0,_.nd)().r(g))}for(var w in f)a=f[w],"style"===w&&"object"===
typeof a?(0,_.Ea)(a,l.style):_.pd[w]||l.setAttribute(w,(0,window.String)(a));(!h||!h.dontclear)&&(0,_.Oa)(c);c.appendChild(l);l=c.lastChild;f.allowtransparency&&(l.allowTransparency=_.r);return l};
_.qd=function(a,c,f){var g=f||{};f=g.attributes||{};(0,_.Fa)(!g.allowPost||!f.onload,"onload is not supported by post iframe");g.rpctoken||(g.rpctoken=_.s);f=c.ownerDocument||_.fb;var h,l=0;do h=g.id||["I",_.rd++,"_",(new window.Date).getTime()].join("");while(f.getElementById(h)&&5>++l);(0,_.Fa)(5>l,"Error creating iframe id");var n,q=f.location.href,l=(0,_.L)(),t=(0,_.Ra)(q);t&&(l._bsh=t);(q=(0,_.Pa)(q))&&(l.jsh=q);q=(0,_.L)();q.id=h;q.parent=f.location.protocol+"//"+f.location.host;var t=(0,_.Ga)(f.location.href,
"id",""),w=(0,_.Ga)(f.location.href,"pfname","");(t=t?w+"/"+t:"")&&(q.pfname=t);g.rpctoken&&(q.rpctoken=g.rpctoken);g.hintInFragment?(0,_.Ea)(l,q):n=l;n=(0,_.Ma)(a,n,q);a=(0,_.L)();(0,_.Ea)(_.sd,a);(0,_.Ea)(g.attributes,a);a.name=a.id=h;a.src=n;if((g||{}).allowPost&&2E3<n.length){n=(0,_.Ha)(n);a.src="";a["data-postorigin"]=n.xc;a=(0,_.od)(f,c,a,h);var x;-1!=window.navigator.userAgent.indexOf("WebKit")&&(x=a.contentWindow.document,x.open(),l=x.createElement("div"),q={},t=h+"_inner",q.name=t,q.src=
"",q.style="display:none",(0,_.od)(f,l,q,t,g));g=(0,_.Ja)(n.kb[0]);n.kb=[];l=(0,_.Ka)(n);n=f.createElement("form");n.action=l;n.method="POST";n.target=h;n.style.display="none";for(h=0;h<g.length;h++)l=f.createElement("input"),l.type="hidden",l.name=g[h][0],l.value=g[h][1],n.appendChild(l);c.appendChild(n);n.submit();n.parentNode.removeChild(n);x&&x.close();c=a}else c=(0,_.od)(f,c,a,h,g);return c};
_.sd={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};_.pd={allowtransparency:_.r,onload:_.r};_.rd=0;
_.td=function(a){_.S.Rg[a]||(_.S.Rg[a]={},_.R.O(a,function(c,f){var g=this.f;if("string"==typeof c&&!(c in{})&&!(g in{})){var h=this.callback,l=_.S.Rg[a][g],n;l&&window.Object.hasOwnProperty.call(l,c)?n=l[c]:window.Object.hasOwnProperty.call(_.S.be,a)&&(n=_.S.be[a]);if(n)return g=window.Array.prototype.slice.call(arguments,1),n._iframe_wrapped_rpc_&&h&&g.push(h),n.apply({},g)}(0,_.ua)(['Unregistered call in window "',window.name,'" for method "',a,'", via proxyId "',c,'" from frame "',g,'".'].join(""));
return _.s}));return _.S.Rg[a]};_.ud=function(a,c,f){function g(g){var l=window.Array.prototype.slice.call(arguments,0),n=l[l.length-1];if("function"===typeof n){var q=n;l.pop()}l.unshift(c,a,q,f);_.R.call.apply(_.R,l)}g._iframe_wrapped_rpc_=_.r;return g};_.vd=function(a,c){var f=(0,_.I)(_.Qa,"watt",(0,_.L)());(0,_.I)(f,a,c)};_.wd=function(){return _.eb.location.origin||_.eb.location.protocol+"//"+_.eb.location.host};
_.xd=function(a){var c=(0,_.Ga)(a.location.href,"urlindex");if(c=(0,_.I)(_.Qa,"fUrl",[])[c]){var f=a.location.hash,c=c+(/#/.test(c)?f.replace(/^#/,"&"):f);a.location.replace(c)}};_.yd=function(){_.S.ll++;return["I",_.S.ll,"_",(new window.Date).getTime()].join("")};
_.zd=function(a){if(0==a.indexOf("http:")||0==a.indexOf("https:")||0==a.indexOf("javascript:"))return a;if(0==a.indexOf("//"))return window.location.protocol+a;if(0==a.indexOf("/"))return window.location.protocol+"//"+window.location.host+a;var c=window.location.protocol+"//"+window.location.host+window.location.pathname,f=c.lastIndexOf("/");return c.substring(0,f+1)+a};_.Ad=function(a){return a instanceof window.Array?a.join(","):a instanceof window.Object?_.P.stringify(a):a};
_.Bd=function(a,c,f){var g={},h=a.indexOf("#");-1==h?(g.hash=_.s,g.xc=a):(g.hash=a.substring(h+1),g.xc=a.substring(0,h));a=g.xc.indexOf("?");-1==a?g.kb=_.s:(g.kb=g.xc.substring(a+1),g.xc=g.xc.substring(0,a));a=f?g.hash?[g.hash]:[]:g.kb?[g.kb]:[];for(var l in c)c.hasOwnProperty(l)&&(h=(0,_.Ad)(c[l]),a.push([(0,_.Cd)(l),(0,_.Cd)(h)].join("=")));f?g.hash=a.join("&"):g.kb=a.join("&");return g.xc+(g.kb?"?"+g.kb:"")+(g.hash?"#"+g.hash:"")};
_.Dd=function(){var a=(0,_.kd)(_.p);return a!==_.p&&a!==_.s&&""!==a?"u/"+a+"/":""};_.Ed=function(a){a&&a.match(_.Fd)&&(0,_.bb)("googleapis.config/gcv",a)};_.Gd=function(a){_.Vc.ph.hs(a)};_.Hd=function(a,c){var f=c||{},g;for(g in a)a.hasOwnProperty(g)&&(f[g]=a[g]);return f};
_.Id=function(a,c,f,g,h){var l=[],n;for(n in a)if(a.hasOwnProperty(n)){var q=c,t=f,w=a[n],x=g,A=(0,_.td)(n);A[q]=A[q]||{};x=_.Q.Fg(x,w);w._iframe_wrapped_rpc_&&(x._iframe_wrapped_rpc_=_.r);A[q][t]=x;l.push(n)}if(h)for(n in _.S.be)_.S.be.hasOwnProperty(n)&&l.push(n);return l.join(",")};_.Jd=function(a,c,f){var g={};if(a&&a._methods){a=a._methods.split(",");for(var h=0;h<a.length;h++){var l=a[h];g[l]=(0,_.ud)(l,c,f)}}return g};
_.Kd=function(a){return a&&a.disableMultiLevelParentRelay?_.u:_.Yc&&_.Yc._open&&"inline"!=a.style&&a.inline!==_.r&&!(a.container&&("string"==typeof a.container&&window.document.getElementById(a.container)||window.document==(a.container.ownerDocument||a.container.document)))};_.Ld=function(a,c){function f(){}f.prototype=c.prototype;a.prototype=new f};
_.Md=function(a,c,f,g,h,l,n,q){if(":"==a.charAt(0)){var t=(0,_.N)("iframes/"+a.substring(1));a={};(0,_.Ea)(t,a);if(t=a.url)t=t||"",t=t.replace(/:session_prefix:/g,(0,_.Dd)()),t=t.replace(/:session_index:/g,(0,_.kd)(_.p)||"0"),t=t.replace(/:socialhost:/g,(0,_.N)("iframes/:socialhost:")),a.url=(0,_.zd)(t);a.params||(a.params={})}else a={url:(0,_.zd)(a)};this.Ga=a;this.openParams=this.wa=c;this.$a=f||{};this.Oa=g;this.j=_.u;c=c.style;if(!this.j)if(c=c&&!_.S.yf[c]&&_.S.Bh[c]){this.k=[];var w=this;c(function(){w.j=
_.r;for(var a=0,c=w.k.length;a<c;++a)w.k[a].call(w)})}else this.j=_.r;this.d={};(0,_.Nd)(this,function(){var a;(a=this.wa.style)&&_.S.yf[a]?a=_.S.yf[a]:a?((0,_.tb)(['Missing handler for style "',a,'". Continuing with default handler.'].join("")),a=_.s):a=_.Od;if(a){var c;if("function"===typeof a)c=a(this);else{var f={};for(c in a){var g=a[c];f[c]="function"===typeof g?_.Q.Fg(a,g,this):g}c=f}for(var n in h)a=c[n],"function"===typeof a&&(0,_.Pd)(this,h[n],_.Q.Fg(c,a))}l&&(0,_.Pd)(this,"close",l)});
this.xa=this.ac=n;this.Wi=(q||[]).slice();n&&this.Wi.unshift(n.aa())};_.Nd=function(a,c){a.j?c.call(a):a.k.push(c)};_.Pd=function(a,c,f){a.d[c]=a.d[c]||[];a.d[c].push(f)};_.Qd=function(a,c){return"number"==typeof c?{value:c,qd:c+"px"}:"100%"==c?{value:100,qd:"100%",wl:_.r}:_.s};_.Rd=function(a){return(0,_.Bd)(a.Ga.url,a.$a,_.u)};
_.Sd=function(a,c,f,g,h,l,n){_.Md.call(this,a,c,f,g,_.Td,h,l,n);this.id=c.id||(0,_.yd)();this.i=c.rpcToken||window.Math.round(1E9*(0,_.ad)());a=this.$a;c={};f=this.Ga.params||{};for(var q in a)"#"==q.charAt(0)&&(c[q.substring(1)]=a[q]),0==q.indexOf("fr-")&&(c[q.substring(3)]=a[q]),"#"==f[q]&&(c[q]=a[q]);for(var t in c)delete a["fr-"+t],delete a["#"+t],delete a[t];this.U=c;this.o={};(0,_.Nd)(this,function(){this.Ob("open");(0,_.Hd)(this.o,this)})};
_.Ud=function(a,c,f,g,h,l,n){_.Md.call(this,a,c,f,g,_.Vd,h,l,n);this.url=a;this.b=_.s;this.z=(0,_.yd)();(0,_.Nd)(this,function(){this.Ob("beforeparentopen");var a=(0,_.Hd)(this.Oa);a._onopen=this.ba;a._ready=this.Lg;a._onclose=this.G;this.$a._methods=(0,_.Id)(a,"..",this.z,this,_.r);var a={},c;for(c in this.$a)a[c]=(0,_.Ad)(this.$a[c]);var f=this.Ga.url;if(this.wa.hideUrlFromParent){c=window.name;var g=f,f=(0,_.Rd)(this),h=a,a={};a._methods=h._methods;a["#opener"]=h["#opener"];a["#urlindex"]=h["#urlindex"];
a["#opener"]&&h["#urlindex"]!=_.p?(a["#opener"]=c+","+a["#opener"],c={url:g,$a:a}):(g=(0,_.I)(_.Qa,"fUrl",[]),h=g.length,g[h]=f,_.Qa.rUrl=_.xd,a["#opener"]=c,a["#urlindex"]=h,c=_.Vc.la(_.eb.location.href),f=(0,_.N)("iframes/relay_url_"+(0,window.encodeURIComponent)(c))||"/_/gapi/sibling/1/frame.html",c={url:c+f,$a:a});f=c.url;a=c.$a}_.Yc._open({url:f,openParams:this.wa,params:a,proxyId:this.z,openedByProxyChain:this.Wi})})};
_.Wd=function(a,c,f,g,h,l,n){_.Md.call(this,a,c,f,g,_.Vd,l,n);this.id=c.id||(0,_.yd)();this.i=h;g._close=this.close;this.onClosed=this.b;this.C=0;(0,_.Nd)(this,function(){this.Ob("beforeparentopen");var a=(0,_.Hd)(this.Oa);this.$a._methods=(0,_.Id)(a,"..",this.z,this,_.r);var a=(0,_.Bd)(this.Ga.url,this.$a,_.u),a=_.Xd.ev(_.fb,a,this.id,{}),c=h.Rl(a);this.canAutoClose=function(a){a(h.ak(c))};h.rm(c,this);this.C=c})};_.Yd=function(a){return _.S.yf[a]};_.Zd=function(a,c){_.S.yf[a]=c}; _.$d=function(a){a=a||{};"auto"===a.height&&(a.height=_.zb.Sh());var c=window&&_.ae&&_.ae.na();c?c.fm(a.width||0,a.height||0):_.Yc&&_.Yc._resizeMe&&_.Yc._resizeMe(a)};_.be=function(a){(0,_.Ed)(a)};_.Xd={};
_.S.L=_.S.L||{};_.S.L.No=function(a){try{return!!a.document}catch(c){}return _.u};_.S.L.yk=function(a){var c=a.parent;return a!=c&&_.S.L.No(c)?_.S.L.yk(c):a};_.S.L.hv=function(a){var c=a.userAgent||"";a=a.product||"";return 0!=c.indexOf("Opera")&&-1==c.indexOf("WebKit")&&"Gecko"==a&&0<c.indexOf("rv:1.")};
if(window.ToolbarApi)_.ae=window.ToolbarApi,_.ae.na=window.ToolbarApi.getInstance,_.ae.prototype=window.ToolbarApi.prototype,_.B=_.ae.prototype,_.B.Rl=_.ae.prototype.openWindow,_.B.ck=_.ae.prototype.closeWindow,_.B.rm=_.ae.prototype.setOnCloseHandler,_.B.ak=_.ae.prototype.canClosePopup,_.B.fm=_.ae.prototype.resizeWindow;else{_.ce=_.s;_.ae=(0,_.v)();_.ae.na=function(){!_.ce&&(window.external&&window.external.GTB_IsToolbar)&&(_.ce=new _.ae);return _.ce};_.B=_.ae.prototype;_.B.Rl=function(a){return window.external.GTB_OpenPopup&&
window.external.GTB_OpenPopup(a)};_.B.ck=function(a){window.external.GTB_ClosePopupWindow&&window.external.GTB_ClosePopupWindow(a)};_.B.rm=function(a,c){window.external.GTB_SetOnCloseHandler&&window.external.GTB_SetOnCloseHandler(a,c)};_.B.ak=function(a){return window.external.GTB_CanClosePopup&&window.external.GTB_CanClosePopup(a)};_.B.fm=function(a,c){return window.external.GTB_ResizeWindow&&window.external.GTB_ResizeWindow(a,c)};window.ToolbarApi=_.ae;window.ToolbarApi.getInstance=_.ae.na};
_.Fd=/^[-_.0-9A-Za-z]+$/;_.Td={open:"open",onready:"ready",close:"close",onresize:"resize",onOpen:"open",onReady:"ready",onClose:"close",onResize:"resize",onRenderStart:"renderstart"};_.Vd={onBeforeParentOpen:"beforeparentopen"};_.Od={onOpen:function(a){var c=a.wa;a.Pa(c.container||c.element);return a},onClose:function(a){a.remove()}};_.Cd=window.encodeURIComponent||window.escape;_.S.Bp=function(a){var c=(0,_.L)();(0,_.Ea)(_.sd,c);(0,_.Ea)(a,c);return c};_.B=_.Md.prototype;_.B.Uh=(0,_.y)("wa");
_.B.Jb=(0,_.y)("$a");_.B.Th=(0,_.y)("Oa");_.B.Vh=(0,_.y)("xa");_.B.ha=function(a,c){(0,_.Nd)(this,function(){(0,_.Pd)(this,a,c)})};_.B.Nc=function(a,c){(0,_.Nd)(this,function(){var f=this.d[a];if(f)for(var g=0,h=f.length;g<h;++g)if(f[g]===c){f.splice(g,1);break}})};
_.B.Ob=function(a,c){var f,g=this.d[a];if(g)for(var h=window.Array.prototype.slice.call(arguments,1),l=0,n=g.length;l<n;++l)try{f=g[l].apply({},h)}catch(q){(0,_.ua)(['Exception when calling callback "',a,'" with exception "',q.name,": ",q.message,'".'].join(""))}return f};(0,_.Ld)(_.Sd,_.Md);_.B=_.Sd.prototype;
_.B.Pa=function(a,c){if(!this.Ga.url)return(0,_.ua)("Cannot open iframe, empty URL."),this;var f=this.id;_.S.Tc[f]=this;var g=(0,_.Hd)(this.Oa);g._ready=this.Lg;g._close=this.close;g._open=this.Sl;g._resizeMe=this.gm;g._renderstart=this.Ol;var h=this.U;this.i&&(h.rpctoken=this.i);h._methods=(0,_.Id)(g,f,"",this,_.r);g=(0,_.Rd)(this);(0,_.Bd)(g,h,_.r);this.V=a="string"===typeof a?window.document.getElementById(a):a;g=(0,_.Rd)(this);g=(0,_.Bd)(g,h,_.r);h={id:f};if(c){h.attributes=c;var l=c.style;if("string"===
typeof l){var n;if(l){n=[];for(var l=l.split(";"),q=0,t=l.length;q<t;++q){var w=l[q];0==w.length&&q+1==t||(w=w.split(":"),2==w.length&&w[0].match(/^[ a-zA-Z_-]+$/)&&w[1].match(/^[ +.%0-9a-zA-Z_-]+$/)?n.push(w.join(":")):(0,_.ua)(['Iframe style "',l[q],'" not allowed.'].join("")))}n=n.join(";")}else n="";c.style=n}}this.wa.allowPost&&(h.allowPost=_.r);this.b=(0,_.qd)(g,a,h);_.S.Tc[f]=this;f=g;_.R.Vg(this.id,this.i);_.R.Wg(this.id,f);return this};_.B.Ba=function(a,c){this.o[a]=c};_.B.aa=(0,_.y)("id");
_.B.ca=(0,_.y)("b");_.B.Sp=(0,_.y)("V");_.B.Oc=(0,_.ba)("V");_.B.Lg=function(a){var c=(0,_.Jd)(a,this.id,"");this.xa&&"function"==typeof this.Oa._ready&&(a._methods=(0,_.Id)(c,this.xa.aa(),this.id,this,_.u),this.Oa._ready(a));(0,_.Hd)(a,this);(0,_.Hd)(c,this);this.Ob("ready",a)};_.B.Ol=function(a){this.Ob("renderstart",a)};_.B.close=function(a){a=this.Ob("close",a);delete _.S.Tc[this.id];return a};_.B.remove=function(){var a=window.document.getElementById(this.id);a&&a.parentNode&&a.parentNode.removeChild(a)};
_.B.Sl=function(a){var c=(0,_.Jd)(a.params,this.id,a.proxyId);delete a.params._methods;"_parent"==a.openParams.anchor&&(a.openParams.anchor=this.V);if((0,_.Kd)(a.openParams))new _.Ud(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain);else{var f=new _.Sd(a.url,a.openParams,a.params,c,c._onclose,this,a.openedByProxyChain),g=this;(0,_.Nd)(f,function(){var a={childId:f.aa()},l=f.o;l._toclose=f.close;a._methods=(0,_.Id)(l,g.id,f.id,f,_.u);c._onopen(a)})}};
_.B.gm=function(a){if(this.Ob("resize",a)===_.p&&this.b){var c=(0,_.Qd)(this,a.width);c!=_.s&&(this.b.style.width=c.qd);a=(0,_.Qd)(this,a.height);a!=_.s&&(this.b.style.height=a.qd);if(this.b.parentElement&&(c!=_.s&&c.wl||a!=_.s&&a.wl))this.b.parentElement.style.display="block"}};(0,_.Ld)(_.Ud,_.Md);_.Ud.prototype.i=(0,_.y)("b");
_.Ud.prototype.ba=function(a){this.b=a.childId;var c=(0,_.Jd)(a,"..",this.b);(0,_.Hd)(c,this);this.close=c._toclose;_.S.Tc[this.b]=this;this.xa&&this.Oa._onopen&&(a._methods=(0,_.Id)(c,this.xa.aa(),this.b,this,_.u),this.Oa._onopen(a))};_.Ud.prototype.Lg=function(a){var c=(0,window.String)(this.b),f=(0,_.Jd)(a,"..",c);(0,_.Hd)(a,this);(0,_.Hd)(f,this);this.Ob("ready",a);this.xa&&this.Oa._ready&&(a._methods=(0,_.Id)(f,this.xa.aa(),c,this,_.u),this.Oa._ready(a))};
_.Ud.prototype.G=function(a){if(this.xa&&this.Oa._onclose)this.Oa._onclose(a);else return a=this.Ob("close",a),delete _.S.Tc[this.b],a};(0,_.Ld)(_.Wd,_.Md);_.Wd.prototype.close=function(a){a=this.Ob("close",a);this.i.ck(this.C);return a};_.Wd.prototype.b=function(){this.Ob("close")};_.S.Tc={};_.S.yf={};_.S.Bh={};_.S.ll=0;_.S.Rg={};_.S.be={};_.S.Og=_.s;_.S.Ng=[];
_.S.tr=function(a){var c=_.u;try{if(a!=_.s)var f=window.parent.frames[a.id],c=f.iframer.id==a.id&&f.iframes.openedId_(_.Yc.id)}catch(g){}try{_.S.Og={origin:this.origin,referer:this.referer,claimedOpenerId:a&&a.id,claimedOpenerProxyChain:a&&a.proxyChain||[],sameOrigin:c};for(a=0;a<_.S.Ng.length;++a)_.S.Ng[a](_.S.Og);_.S.Ng=[]}catch(h){}};_.S.Kp=function(a){var c=a&&a.xa,f=_.s;c&&(f={},f.id=c.aa(),f.proxyChain=a.Wi);return f};_.R.O("_noop_echo",function(){this.callback(_.S.Kp(_.S.Tc[this.f]))});
if(window.parent!=window){_.de=_.Q.oa();_.de.gcv&&(0,_.Ed)(_.de.gcv);_.ee=_.de.jsh;_.ee&&(0,_.Gd)(_.ee);(0,_.Hd)((0,_.Jd)(_.de,"..",""),_.Yc);(0,_.Hd)(_.de,_.Yc);window.setTimeout(function(){_.R.call("..","_noop_echo",_.S.tr)},0)}_.S.ra=_.Yd;_.S.ma=_.Zd;_.S.es=_.be;_.S.Yc=_.$d;_.S.vp=function(a){return _.S.Bh[a]};_.S.hj=function(a,c){_.S.Bh[a]=c};_.S.Kr=_.$d;_.S.ms=_.be;_.S.qg={};_.S.qg.get=_.Yd;_.S.qg.set=_.Zd;_.S.Do=function(a,c){(0,_.td)(a);_.S.be[a]=c||window[a]};_.S.av=function(a){delete _.S.be[a]};
_.S.open=function(a,c,f,g,h,l){3==arguments.length?g={}:4==arguments.length&&"function"===typeof g&&(h=g,g={});var n="bubble"===c.style&&_.ae&&_.ae.na();return n?new _.Wd(a,c,f,g,n,h,l):(0,_.Kd)(c)?new _.Ud(a,c,f,g,h,l):new _.Sd(a,c,f,g,h,l)};_.S.close=function(a,c){_.Yc&&_.Yc._close&&_.Yc._close(a,c)};
_.S.Sb=function(a,c,f){2==arguments.length&&"function"===typeof h&&(f=c,c={});var g=a||{};"height"in g||(g.height=_.zb.Sh());var h=c||{};g._methods=(0,_.Id)(h,"..","",_.Yc,_.r);_.Yc&&_.Yc._ready&&_.Yc._ready(g,f)};_.S.tk=function(a){_.S.Og?a(_.S.Og):_.S.Ng.push(a)};_.S.qr=function(a){return!!_.S.Tc[a]};_.S.zp=function(){return["https://ssl.gstatic.com/gb/js/",(0,_.N)("googleapis.config/gcv")].join("")};
_.S.zr=function(a){var c={mouseover:1,mouseout:1};if(_.Yc._event)for(var f=0;f<a.length;f++){var g=a[f];g in c&&_.Q.Fe(window.document,g,function(a){_.Yc._event({event:a.type,timestamp:(new window.Date).getTime()})},_.r)}};_.S.is=_.Gd;_.S.gj=function(a){_.Vc.ph.gj(a)};_.S.pv=(0,_.v)();_.S.Mq=_.Yc;
(0,_.O)("iframes.allow",_.S.Do);(0,_.O)("iframes.callSiblingOpener",_.S.Mo);(0,_.O)("iframes.registerForOpenedSibling",_.S.Ar);(0,_.O)("iframes.close",_.S.close);(0,_.O)("iframes.getGoogleConnectJsUri",_.S.zp);(0,_.O)("iframes.getHandler",_.S.ra);(0,_.O)("iframes.getDeferredHandler",_.S.vp);(0,_.O)("iframes.getParentInfo",_.S.tk);(0,_.O)("iframes.iframer",_.S.Mq);(0,_.O)("iframes.open",_.S.open);(0,_.O)("iframes.openedId_",_.S.qr);(0,_.O)("iframes.propagate",_.S.zr);(0,_.O)("iframes.ready",_.S.Sb);
(0,_.O)("iframes.resize",_.S.Yc);(0,_.O)("iframes.setGoogleConnectJsVersion",_.S.es);(0,_.O)("iframes.setBootstrapHint",_.S.gj);(0,_.O)("iframes.setJsHint",_.S.is);(0,_.O)("iframes.setHandler",_.S.ma);(0,_.O)("iframes.setDeferredHandler",_.S.hj);(0,_.O)("IframeBase",_.Md);(0,_.O)("IframeBase.prototype.addCallback",_.Md.prototype.ha);(0,_.O)("IframeBase.prototype.getMethods",_.Md.prototype.Th);(0,_.O)("IframeBase.prototype.getOpenerIframe",_.Md.prototype.Vh);
(0,_.O)("IframeBase.prototype.getOpenParams",_.Md.prototype.Uh);(0,_.O)("IframeBase.prototype.getParams",_.Md.prototype.Jb);(0,_.O)("IframeBase.prototype.removeCallback",_.Md.prototype.Nc);(0,_.O)("Iframe",_.Sd);(0,_.O)("Iframe.prototype.close",_.Sd.prototype.close);(0,_.O)("Iframe.prototype.exposeMethod",_.Sd.prototype.Ba);(0,_.O)("Iframe.prototype.getId",_.Sd.prototype.aa);(0,_.O)("Iframe.prototype.getIframeEl",_.Sd.prototype.ca);(0,_.O)("Iframe.prototype.getSiteEl",_.Sd.prototype.Sp);
(0,_.O)("Iframe.prototype.openInto",_.Sd.prototype.Pa);(0,_.O)("Iframe.prototype.remove",_.Sd.prototype.remove);(0,_.O)("Iframe.prototype.setSiteEl",_.Sd.prototype.Oc);(0,_.O)("Iframe.prototype.addCallback",_.Sd.prototype.ha);(0,_.O)("Iframe.prototype.getMethods",_.Sd.prototype.Th);(0,_.O)("Iframe.prototype.getOpenerIframe",_.Sd.prototype.Vh);(0,_.O)("Iframe.prototype.getOpenParams",_.Sd.prototype.Uh);(0,_.O)("Iframe.prototype.getParams",_.Sd.prototype.Jb);
(0,_.O)("Iframe.prototype.removeCallback",_.Sd.prototype.Nc);(0,_.O)("IframeProxy",_.Ud);(0,_.O)("IframeProxy.prototype.getTargetIframeId",_.Ud.prototype.i);(0,_.O)("IframeProxy.prototype.addCallback",_.Ud.prototype.ha);(0,_.O)("IframeProxy.prototype.getMethods",_.Ud.prototype.Th);(0,_.O)("IframeProxy.prototype.getOpenerIframe",_.Ud.prototype.Vh);(0,_.O)("IframeProxy.prototype.getOpenParams",_.Ud.prototype.Uh);(0,_.O)("IframeProxy.prototype.getParams",_.Ud.prototype.Jb);
(0,_.O)("IframeProxy.prototype.removeCallback",_.Ud.prototype.Nc);(0,_.O)("IframeWindow",_.Wd);(0,_.O)("IframeWindow.prototype.close",_.Wd.prototype.close);(0,_.O)("IframeWindow.prototype.onClosed",_.Wd.prototype.b);(0,_.O)("iframes.util.getTopMostAccessibleWindow",_.S.L.yk);(0,_.O)("iframes.handlers.get",_.S.qg.get);(0,_.O)("iframes.handlers.set",_.S.qg.set);(0,_.O)("iframes.resizeMe",_.S.Kr);(0,_.O)("iframes.setVersionOverride",_.S.ms);

_.fe=function(a){var c=(0,_.Ta)();return c?c(a):_.u};_.ge=(0,_.I)(_.Qa,"rw",(0,_.L)());
_.he=function(a,c){var f=_.ge[a];f&&f.state<c&&(f.state=c)};_.ie=function(a){a=(a=_.ge[a])?a.oid:_.p;if(a){var c=_.fb.getElementById(a);c&&c.parentNode.removeChild(c);delete _.ge[a];(0,_.ie)(a)}};_.je=function(a){a=a.style;a.textIndent="0";a.margin="0";a.padding="0";a.background="transparent";a.borderStyle="none";a.cssFloat="none";a.styleFloat="none";a.lineHeight="normal";a.fontSize="1px";a.verticalAlign="baseline"};
_.ke=function(a){a=a.wa.container;"string"===typeof a&&(a=window.document.getElementById(a));return a};_.le=function(a){var c=a.clientWidth;return"position:absolute;top:-10000px;width:"+(c?c+"px":a.style.width||"300px")+";margin:0px;border-style:none;"};
_.ne=function(a,c){var f={};f.width=c?c.width:a.width;f.height=c?c.height:a.height;var g=a.ca(),h=a.aa();(0,_.he)(h,2);(h=_.ge[h])&&(h.args=f);a:{h=g.parentNode;f=f||{};if((0,_.fe)()){if("number"===typeof _.Qa.ucs)break a;var l=g.id;if(l){var n;n=(n=_.ge[l])?n.state:_.p;if(1===n||4===n)break a;(0,_.ie)(l)}}n=f.width;f=f.height;(0,_.je)(h);h.style.display="inline-block";g=g.style;g.position="static";g.left=0;g.top=0;g.visibility="visible";n&&(g.width=n+"px");f&&(g.height=f+"px");l&&(0,_.he)(l,3)}(l= c?c.title:_.s)&&a.ca().setAttribute("title",l)};
_.oe={open:function(a){var c=(0,_.ke)(a);return a.Pa(c,{style:(0,_.le)(c,a)})},attach:function(a,c){var f=(0,_.ke)(a),g=c.id,h=c.getAttribute("data-postorigin")||c.src,l=/#(?:.*&)?rpctoken=(\d+)/.exec(h),l=l&&l[1];a.id=g;a.i=l;a.V=c.parentNode;a.b=c;_.S.Tc[g]=a;l=(0,_.Hd)(a.Oa);l._ready=a.Lg;l._close=a.close;l._open=a.Sl;l._resizeMe=a.gm;l._renderstart=a.Ol;(0,_.Id)(l,g,"",a,_.r);_.R.Vg(a.id,a.i);_.R.Wg(a.id,h);var f=_.S.Bp({style:(0,_.le)(f,a)}),n;for(n in f)window.Object.prototype.hasOwnProperty.call(f, n)&&("style"==n?a.b.style.cssText=f[n]:a.b.setAttribute(n,f[n]))}};_.oe.onready=_.ne;_.oe.onRenderStart=_.ne;_.oe.close=function(a){var c=a.V;c&&c.removeChild(a.ca())};_.S.ma("inline",_.oe);


_.pe=function(a){var c;a.match(/^https?%3A/i)&&(c=(0,window.decodeURIComponent)(a));a=c?c:a;return(0,_.Na)(window.document,a)};_.qe=function(a){a=a||"canonical";for(var c=window.document.getElementsByTagName("link"),f=0,g=c.length;f<g;f++){var h=c[f],l=h.getAttribute("rel");if(l&&l.toLowerCase()==a&&(h=h.getAttribute("href")))return(0,_.pe)(h)}return window.location.href};_.re=function(a,c,f,g){return(a="string"==typeof a?a:_.p)?(0,_.pe)(a):(0,_.qe)(g)};
_.se=function(a){return"string"==typeof a?""!=a&&"0"!=a&&"false"!=a.toLowerCase():!!a};_.te=function(a){var c=(0,window.parseInt)(a,10);if(c==a)return(0,window.String)(c)};_.ue=function(a){if((0,_.se)(a))return"true"};_.ve=function(a){return"string"==typeof a&&_.we[a.toLowerCase()]?a.toLowerCase():"standard"};_.xe=function(a,c){return"tall"==(0,_.ve)(c)?"true":a==_.s||(0,_.se)(a)?"true":"false"};_.ye=function(a,c,f){a==_.s&&f&&(a=f.db,a==_.s&&(a=f.gwidget&&f.gwidget.db));return a||_.p};
_.ze=function(a,c,f){a==_.s&&f&&(a=f.ecp,a==_.s&&(a=f.gwidget&&f.gwidget.ecp));return a||_.p};_.we={tall:{"true":{width:50,height:60},"false":{width:50,height:24}},small:{"false":{width:24,height:15},"true":{width:70,height:15}},medium:{"false":{width:32,height:20},"true":{width:90,height:20}},standard:{"false":{width:38,height:24},"true":{width:106,height:24}}};
_.Ae={href:[_.re,"url"],width:[_.te],size:[_.ve],resize:[_.ue],autosize:[_.ue],count:[function(a,c){return(0,_.xe)(c.count,c.size)}],db:[_.ye],ecp:[_.ze],textcolor:[function(a){if("string"==typeof a&&a.match(/^[0-9A-F]{6}$/i))return a}],drm:[_.ue],recommendations:[],fu:[],ad:[_.ue],cr:[_.te],ag:[_.te],"fr-ai":[],"fr-sigh":[]};


_.Be=(0,_.Sa)();
_.Ce=function(a,c){if(!_.De){var f=(0,_.N)("iframes/:socialhost:"),g=(0,_.kd)(_.p)||"0",h=(0,_.kd)(_.p);_.De={socialhost:f,session_index:g,session_prefix:h!==_.p&&h!==_.s&&""!==h?"u/"+h+"/":"",im_prefix:(0,_.N)("googleapis.config/signedIn")===_.u?"_/im/":""}}return _.De[c]||""};_.Ee=function(a,c,f){return(0,_.re)(a,c,f,c.action?_.p:"publisher")};_.Fe=function(){return window.location.origin||window.location.protocol+"//"+window.location.host};
_.Ge=function(a){var c=_.p;"number"===typeof a?c=a:"string"===typeof a&&(c=(0,window.parseInt)(a,10));return c};_.He=function(a,c){if("string"==typeof a){a=a.toLowerCase();var f;for(f=0;f<c.length;f++)if(c[f]==a)return a}};_.Ie=function(a){return(0,_.He)(a,_.Je)};_.Ke=function(a){return(0,_.He)(a,_.Le)};_.Me=function(a){a.source=[_.s,"source"];a.expandTo=[_.s,"expandTo"];a.align=[_.Ke];a.annotation=[_.Ie];a.origin=[_.Fe]};
_.Ne=function(a){if(_.Ca.test(window.Object.keys))return window.Object.keys(a);var c=[],f;for(f in a)(0,_.Da)(a,f)&&c.push(f);return c};
_.Oe=function(a,c){_.Pe.ps0=(new window.Date).getTime();(0,_.Qe)("ps0");var f=("string"===typeof a?window.document.getElementById(a):a)||_.fb,g;g=_.fb.documentMode;if(f.querySelectorAll&&(!g||8<g)){g=c?[c]:(0,_.Ne)(_.Re).concat((0,_.Ne)(_.Se)).concat((0,_.Ne)(_.Te));for(var h=[],l=0;l<g.length;l++){var n=g[l];h.push(".g-"+n,"g\\:"+n)}g=f.querySelectorAll(h.join(","))}else g=f.getElementsByTagName("*");f=(0,_.L)();for(h=0;h<g.length;h++){l=g[h];var q=l,n=c,t=q.nodeName.toLowerCase(),w=_.p;q.getAttribute("data-gapiscan")?
n=_.s:(0==t.indexOf("g:")?w=t.substr(2):(q=(q=(0,window.String)(q.className||q.getAttribute("class")))&&_.Ue.exec(q))&&(w=q[1]),n=w&&(_.Re[w]||_.Se[w]||_.Te[w])&&(!n||w===n)?w:_.s);n&&(l.setAttribute("data-gapiscan",_.r),(0,_.I)(f,n,[]).push(l))}for(var x in f)_.Ve.push(x);_.Pe.ps1=(new window.Date).getTime();(0,_.Qe)("ps1");(x=_.Ve.join(":"))&&_.gb.load(x,_.p);var A,l=[];for(A in f){h=f[A];g=0;for(x=h.length;g<x;g++){for(var q=h[g],n=A,t=w=q,q=(0,_.L)(),F=0!=t.nodeName.toLowerCase().indexOf("g:"),
J=0,K=t.attributes.length;J<K;J++){var M=t.attributes[J],V=M.name,M=M.value;0<=_.xb.call(_.We,V)||(F&&0!=V.indexOf("data-")||"null"===M)||(F&&(V=V.substr(5)),q[V.toLowerCase()]=M)}t=t.style;(F=(0,_.Ge)(t&&t.height))&&(q.height=(0,window.String)(F));(t=(0,_.Ge)(t&&t.width))&&(q.width=(0,window.String)(t));(0,_.Xe)(n,w,q,l,x)}}};
_.Ye=function(a,c){var f=(0,_.I)(_.Qa,"watt",(0,_.L)())[a];c&&f?(f(c),(f=c.iframeNode)&&f.setAttribute("data-gapiattached",_.r)):_.gb.load(a,function(){var f=(0,_.I)(_.Qa,"watt",(0,_.L)())[a],h=c&&c.iframeNode;!h||!f?(0,_.gb[a].go)(h&&h.parentNode):(f(c),h.setAttribute("data-gapiattached",_.r))})};
_.Xe=function(a,c,f,g,h){switch((0,_.Ze)(c,a)){case 0:case 1:g={};g.iframeNode=c;g.userParams=f;(0,_.Ye)(a,g);break;case 2:if(c.parentNode){var l=_.r;f.dontclear&&(l=_.u);delete f.dontclear;var n;var q;c:{var t=a,w=a;"plus"==a&&f.action&&(t=a+"_"+f.action,w=a+"/"+f.action);q=(0,_.N)("iframes/"+t+"/url");if(!q){if((0,_.I)(_.Qa,"SM",(0,_.L)())[t]){q=_.s;break c}q=":socialhost:/_/widget/render/"+w}q=q.replace(_.$e,_.Ce)}if(q){t={};(0,_.Ea)(f,t);t.hl=(0,_.N)("lang")||"en-US";t.origin=(0,_.Fe)();t.exp=
(0,_.N)("iframes/"+a+"/params/exp");if(w=(0,_.N)("iframes/"+a+"/params/location"))for(var x=0;x<w.length;x++){var A=w[x];t[A]=_.eb.location[A]}switch(a){case "plus":t.url=(0,_.Ee)(t.href,f,_.s);delete t.href;break;case "plusone":case "recobox":t.url=f.href?(0,_.pe)(f.href):(0,_.qe)();t.db=(0,_.ye)(f.db,_.p,(0,_.N)());t.ecp=(0,_.ze)(f.ecp,_.p,(0,_.N)());delete t.href;break;case "signin":t.url=(0,_.qe)()}t.hl=(0,_.N)("lang")||"en-US";_.Qa.ILI&&(t.iloader="1");delete t["data-onload"];delete t.rd;t.gsrc=
(0,_.N)("iframes/:source:");w=(0,_.N)("inline/css");"undefined"!==typeof w&&(0<h&&w>=h)&&(t.ic="1");w=/^#|^fr-/;h={};for(var F in t)(0,_.Da)(t,F)&&w.test(F)&&(h[F.replace(w,"")]=t[F],delete t[F]);F=[].concat(_.af);w=(0,_.N)("iframes/"+a+"/methods");"object"===typeof w&&_.Ca.test(w.push)&&(F=F.concat(w));for(n in f)if((0,_.Da)(f,n)&&/^on/.test(n)&&("plus"!=a||"onconnect"!=n))F.push(n),delete t[n];delete t.callback;h._methods=F.join(",");n=(0,_.Ma)(q,t,h)}else n=_.s;n?(f.rd?F=c:(F=window.document.createElement("div"),
c.setAttribute("data-gapistub",_.r),F.style.cssText="position:absolute;width:100px;left:-10000px;",c.parentNode.insertBefore(F,c)),F.id||(c=F,(0,_.I)(_.Be,a,0),q="___"+a+"_"+_.Be[a]++,c.id=q),c=(0,_.L)(),c[">type"]=a,(0,_.Ea)(f,c),F.setAttribute("data-gwattr",(0,_.La)(c).join(":")),c=F,F={allowPost:1,attributes:_.bf},F.dontclear=!l,c=(0,_.qd)(n,c,F),l={},l.userParams=f,l.url=n,l.type=a,l.iframeNode=c,l.id=c.getAttribute("id"),f=l.id,c=(0,_.L)(),c.id=f,c.userParams=l.userParams,c.url=l.url,c.type=
l.type,c.state=1,_.ge[f]=c,f=l):f=_.s}else f=_.s;f&&((l=f.id)&&g.push(l),(0,_.Ye)(a,f))}};_.Ze=function(a,c){if(a&&1===a.nodeType&&c){if(_.Se[c])return 1;var f;if(f=_.Te[c])if(f=!!_.cf[a.nodeName.toLowerCase()])f=(f=a.innerHTML)&&f.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")?_.r:_.u;if(f)return 0;if(_.Re[c])return 2}return _.s};_.df=function(a,c,f,g){_.ef[f]=_.ef[f]||!!g;(0,_.I)(_.ff,f,[]);_.ff[f].push([a,c])};_.Qe=function(a,c,f){var g=_.gf.r;"function"===typeof g?g(a,c,f):g.push([a,c,f])};
_.hf=function(a,c,f,g){"_p"==c&&(0,_.m)((0,window.Error)("m`_p"));(0,_.jf)(c,f)[a]=g||(new window.Date).getTime();(0,_.Qe)(a,c,f)};_.jf=function(a,c){var f=(0,_.I)(_.kf,a,(0,_.L)());return(0,_.I)(f,c,(0,_.L)())};_.lf=function(a,c,f){var g=_.s;c&&f&&(g=(0,_.jf)(c,f)[a]);return g||_.Pe[a]};_.mf=function(a){this.t={};this.tick=function(a,f,g){this.t[a]=[g!=_.p?g:(new window.Date).getTime(),f]};this.tick("start",_.s,a)};_.nf=function(a,c){this.type=!a?"g":"_p"==a?"m":"w";this.name=a;this.b=c};
_.of=function(a){var c=[];c.push("l"+((0,_.N)("isPlusUser")?"1":"0"));var f="m"+(_.pf?"1":"0");c.push(f);if("m"==a.type)c.push("p"+a.b);else if("w"==a.type){var g="n"+a.b;c.push(g);"0"==a.b&&c.push(f+g)}return c};_.qf=function(a,c,f){for(var g=new _.nf(c,f),h=(0,_.I)(_.rf,g.key(),(0,_.L)()),l=_.ff[a]||[],n=0;n<l.length;++n){var q=l[n],t=h,w=q[0],x=a,A=c,F=f,q=(0,_.lf)(q[1],A,F),x=(0,_.lf)(x,A,F);t[w]=q&&x?x-q:_.s}_.ef[a]&&_.sf&&((0,_.tf)(_.uf),(0,_.tf)(g))};
_.vf=function(a,c){c=c||[];for(var f=[],g=0;g<c.length;g++)f.push(a+c[g]);return f};
_.tf=function(a){var c=_.eb.__gapi_jstiming__;c.sn=_.wf[a.type];var f=new c.Timer(0),g;a:{switch(a.type){case "g":g="global";break a;case "m":g=a.b;break a;case "w":g=a.name;break a}g=_.p}f.name=g;g=_.u;var h=a.key(),l=_.rf[h];f.tick("_start",_.s,0);for(var n in l)f.tick(n,"_start",l[n]),g=_.r;_.rf[h]=(0,_.L)();if(g){n=[];g=(0,_.N)("lexps");n=n.concat((0,_.vf)("e",g));n=n.concat((0,_.vf)("",(0,_.of)(a)));for(h=0;h<_.xf.length;h++)l=_.xf[h],0<=_.xb.call(g,l)&&(n=n.concat((0,_.vf)(l?"e"+l:"",(0,_.of)(a))));
n=(0,_.vf)("abc_",n);c.report(f,{e:n.join(",")})}};_.yf=function(a){var c=(0,_.N)(a);return"undefined"!==typeof c?c:(0,_.N)("gwidget/"+a)};_.zf=function(a){return function(c){var f=a;"number"===typeof c?f=c:"string"===typeof c&&(f=c.indexOf("px"),-1!=f&&(c=c.substring(0,f)),f=(0,window.parseInt)(c,10));return f}};_.Af=function(a){"string"===typeof a&&(a=window[a]);return"function"===typeof a?a:_.s};_.Bf=function(a,c,f,g){return _.S.open(a,c,f,g)};
_.Cf=function(a,c){for(var f in _.Df)if(_.Df.hasOwnProperty(f)){var g=_.Df[f][1];g&&!c.hasOwnProperty(g)&&(c[g]=a[g])}return c};_.Ef=function(a,c){var f={},g;for(g in a)a.hasOwnProperty(g)&&(f[a[g][1]||g]=(a[g]&&a[g][0]||_.Ff)(c[g],c,_.Gf));return f};_.Ff=function(a){return a};_.Hf=function(){};_.De=_.s;_.$e=/:([a-zA-Z_]+):/g;_.af="onPlusOne _ready _close,_open _resizeMe _renderstart oncircled".split(" ");_.Je="inline bubble none only pp vertical-bubble".split(" ");_.Le=["left","right"];
_.We=["style","data-gapiscan"];_.bf={style:"position:absolute;top:-10000px;width:300px;margin:0px;borderStyle:none"};_.Ue=/(?:^|\s)g-((\S)*)(?:$|\s)/;_.cf={button:_.r,div:_.r,span:_.r};_.Re=(0,_.I)(_.Qa,"SW",(0,_.L)());_.Se=(0,_.I)(_.Qa,"SA",(0,_.L)());_.Te=(0,_.I)(_.Qa,"SM",(0,_.L)());_.Ve=(0,_.I)(_.Qa,"FW",[]);
(0,_.I)(_.gb,"platform",{}).go=_.Oe;_.gf=(0,_.I)(_.Qa,"perf",(0,_.L)());_.Pe=(0,_.I)(_.gf,"g",(0,_.L)());_.kf=(0,_.I)(_.gf,"i",(0,_.L)());(0,_.I)(_.gf,"r",[]);_.ef=(0,_.L)();_.ff=(0,_.L)();_.If=new _.mf;window.__gapi_jstiming__={Timer:_.mf,load:_.If};if(window.performance&&window.performance.timing){_.Jf=window.performance.timing;_.Kf=window.__gapi_jstiming__.load;_.Lf=_.Jf.navigationStart;_.Mf=_.Jf.responseStart;0<_.Lf&&_.Mf>=_.Lf&&(_.Kf.tick("_wtsrt",_.p,_.Lf),_.Kf.tick("wtsrt_","_wtsrt",_.Mf),_.Kf.tick("tbsd_","wtsrt_"))}
try{_.Nf=_.s;window.chrome&&window.chrome.csi&&(_.Nf=window.Math.floor(window.chrome.csi().pageT),_.Kf&&0<_.Lf&&(_.Kf.tick("_tbnd",_.p,window.chrome.csi().startE),_.Kf.tick("tbnd_","_tbnd",_.Lf)));_.Nf==_.s&&window.gtbExternal&&(_.Nf=window.gtbExternal.pageT());_.Nf==_.s&&window.external&&(_.Nf=window.external.pageT,_.Kf&&0<_.Lf&&(_.Kf.tick("_tbnd",_.p,window.external.startE),_.Kf.tick("tbnd_","_tbnd",_.Lf)));_.Nf&&(window.__gapi_jstiming__.pt=_.Nf)}catch(Of){};
if(window.__gapi_jstiming__){window.__gapi_jstiming__.Zj={};window.__gapi_jstiming__.Gr=1;_.Pf=function(a,c,f){var g=a.t[c],h=a.t.start;if(g&&(h||f))return g=a.t[c][0],f!=_.p?h=f:h=h[0],g-h};window.__gapi_jstiming__.getTick=_.Pf;window.__gapi_jstiming__.getLabels=function(a){var c=[],f;for(f in a.t)c.push(f);return c};_.Qf=function(a,c,f){var g="";window.__gapi_jstiming__.pt&&(g+="&srt="+window.__gapi_jstiming__.pt);try{window.external&&window.external.tran?g+="&tran="+window.external.tran:window.gtbExternal&&
window.gtbExternal.tran?g+="&tran="+window.gtbExternal.tran():window.chrome&&window.chrome.csi&&(g+="&tran="+window.chrome.csi().tran)}catch(h){}var l=window.chrome;if(l&&(l=l.loadTimes)){l().wasFetchedViaSpdy&&(g+="&p=s");if(l().wasNpnNegotiated){var g=g+"&npn=1",n=l().npnNegotiatedProtocol;n&&(g+="&npnv="+(window.encodeURIComponent||window.escape)(n))}l().wasAlternateProtocolAvailable&&(g+="&apa=1")}var q=a.t,t=q.start,l=[],n=[],w;for(w in q)if("start"!=w&&0!=w.indexOf("_")){var x=q[w][1];x?q[x]&&
n.push(w+"."+(0,_.Pf)(a,w,q[x][0])):t&&l.push(w+"."+(0,_.Pf)(a,w))}if(c)for(var A in c)g+="&"+A+"="+c[A];(c=f)||(c="https:"==window.document.location.protocol?"https://csi.gstatic.com/csi":"http://csi.gstatic.com/csi");a=[c,"?v=3","&s="+(window.__gapi_jstiming__.sn||"gwidget")+"&action=",a.name,n.length?"&it="+n.join(","):"","",g,"&rt=",l.join(",")].join("");if(!a)return"";var g=new window.Image,F=window.__gapi_jstiming__.Gr++;window.__gapi_jstiming__.Zj[F]=g;g.onload=g.onerror=function(){window.__gapi_jstiming__&&
delete window.__gapi_jstiming__.Zj[F]};g.src=a;g=_.s;return a};window.__gapi_jstiming__.report=function(a,c,f){if("prerender"==window.document.webkitVisibilityState){var g=_.u,h=function(){if(!g){c?c.prerender="1":c={prerender:"1"};var l;"prerender"==window.document.webkitVisibilityState?l=_.u:((0,_.Qf)(a,c,f),l=_.r);l&&(g=_.r,window.document.removeEventListener("webkitvisibilitychange",h,_.u))}};window.document.addEventListener("webkitvisibilitychange",h,_.u);return""}return(0,_.Qf)(a,c,f)}};
_.xf=[73,74,77,78];_.wf={g:"gapi_global",m:"gapi_module",w:"gwidget"};_.nf.prototype.key=function(){switch(this.type){case "g":return this.type;case "m":return this.type+"."+this.b;case "w":return this.type+"."+this.name+this.b}};_.uf=new _.nf;_.pf=window.navigator.userAgent.match(/iPhone|iPad|Android|PalmWebOS|Maemo|Bada/);_.rf=(0,_.I)(_.gf,"_c",(0,_.L)());_.sf=window.Math.random()<((0,_.N)("csi/rate")||0);(0,_.df)("blt","bs0","bs1");(0,_.df)("psi","ps0","ps1");(0,_.df)("rpcqi","rqe","rqd");
(0,_.df)("mli","ml0","ml1");(0,_.df)("mei","me0","me1",_.r);(0,_.df)("wci","wrs","wdc");(0,_.df)("wdi","wrs","wrdi");(0,_.df)("wdt","bs0","wrdt");(0,_.df)("wri","wrs","wrri",_.r);(0,_.df)("wrt","bs0","wrrt");(0,_.df)("wji","wje0","wje1",_.r);(0,_.df)("wjli","wjl0","wjl1");(0,_.df)("whi","wh0","wh1",_.r);_.Rf=_.gf.r;if("function"!==typeof _.Rf){for(_.Sf;_.Sf=_.Rf.shift();)_.qf.apply(_.s,_.Sf);_.gf.r=_.qf};
_.Uf=["div"];_.Vf="onload";_.Wf=_.r;_.Gf=_.s;_.Gf=(0,_.N)();(0,_.N)("gwidget");_.Xf=(0,_.yf)("parsetags");_.Vf="explicit"===_.Xf||"onload"===_.Xf?_.Xf:_.Vf;_.Yf=(0,_.yf)("google_analytics");"undefined"!==typeof _.Yf&&(_.Wf=!!_.Yf);_.Zf={};_.Zf.width=[(0,_.zf)(450)];_.Zf.height=[(0,_.zf)(24)];_.Zf.callback=[_.Af];_.Zf.onready=[_.Af];_.Zf.lang=[function(){return(0,_.yf)("lang")||"en-US"},"hl"];_.Zf.iloader=[function(){return _.Qa.ILI},"iloader"];_.Df=_.Zf;
_.Tf={Na:function(a){function c(a){for(var c={},f=0;f<a.length;++f)c[a[f].toLowerCase()]=1;c[h.Is]=1;h.Zq=c}function f(){"onload"===_.Vf&&q.go()}var g,h={};h.Db=a[0];h.Bj=-1;h.Qm="___"+h.Db+"_";h.Is="g:"+h.Db;h.lv="g-"+h.Db;h.dm=[];h.Ga={};h.th=[];h.Jh=[];a[1]&&(h.rr=a[1]);h.Ga=a[2]||{};for(var l in _.Df)_.Df.hasOwnProperty(l)&&!h.Ga.hasOwnProperty(l)&&(h.Ga[l]=_.Df[l]);a[3]&&(h.th=a[3]);a[4]&&c(a[4]);a[5]&&(h.qe=a[5]);h.zv=a[7]===_.r;h.xr=a[8];h.Zq||c(_.Uf);if(a=a[6])if("number"==typeof a.length){h.Jh=
a;for(var n=a.length-1;0<=n;--n)h.Ga[a[n]]=[_.Af]}else for(n in a)a.hasOwnProperty(n)&&!h.Ga.hasOwnProperty(n)&&(h.Jh.push(n),h.Ga[n]=a[n]);h.Ui=function(a){function c(){ms||(ms=_.r,f(),ns&&(0,_.hf)("wrrt",oc,pc),(0,_.hf)("wrri",oc,pc))}function f(){os||(os=_.r,$b.ca(),ns&&(0,_.hf)("wrdt",oc,pc),(0,_.hf)("wrdi",oc,pc))}function g(a){a=a||$b;var c=(0,_.Qd)($b,a.width);c&&Ai.style.width!=c.qd&&(Ai.style.width=c.qd);if((a=(0,_.Qd)($b,a.height))&&Ai.style.height!=a.qd)Ai.style.height=a.qd}h.Bj++;(0,_.hf)("wrs",
h.Db,(0,window.String)(h.Bj));var l=[];h.qe&&(l[0]=a.element,l[1]=a.Sg,h.qe("s",l),a.Sg=l[1]);var n=a.element,q=n.parentNode,t=a.Ga;if(0===a.Sg){var ra=window.document.createElement("div");q.insertBefore(ra,n);q.removeChild(n);n=ra}ra=n.style;if(n.id){if(0===n.id.indexOf(h.Qm)){var fa=n.nextSibling;fa&&(fa.getAttribute&&fa.getAttribute("data-gapistub"))&&q.removeChild(fa);ra.cssText=""}}else{var q=n,fa=h.Qm,ta=h.Db,ub=(0,_.Sa)();window.Object.prototype.hasOwnProperty.call(ub,ta)||(ub[ta]=0);var Bi=
ub[ta];ub[ta]=Bi+1;q.id=fa+Bi}t.height&&(ra.height=t.height+"px");t.width&&(ra.width=t.width+"px");ra.display||(ra.display="inline-block");(0,_.je)(n);var me=":"+h.Db;":plus"==me&&(a.pe&&a.pe.action)&&(me+="_"+a.pe.action);var ra={},q=h.th[0],fa=t.callback,ac=h.th[1];if(ac&&_.Wf)var nB=fa||(0,_.v)(),fa=function(a){var c=ac(a);if(c&&window._gat)try{var f=window._gat._getTrackerByName("~0");f&&"UA-XXXXX-X"!=f._getAccount()?f._trackSocial("Google",c,a.href||_.s):window._gaq&&window._gaq.push(["_trackSocial",
"Google",c,a.href||_.s])}catch(g){}nB(a)};q&&fa&&(ra[q]=fa);q=h.Jh;for(fa=q.length-1;0<=fa;--fa){var Ec=q[fa];(ta=t[Ec])&&(ra[Ec]=ta)}q={};for(Ec in a.pe)a.pe[Ec]!=_.s&&(q[Ec]=a.pe[Ec]);Ec={container:n.id,renderData:a.Fr,style:"inline",height:t.height,width:t.width};if(!_.S.ra("attach")){var fa={},Ci=_.S.ra("inline"),Di;for(Di in Ci)Ci.hasOwnProperty(Di)&&(fa[Di]=Ci[Di]);fa.open=function(a){var c=window.document.getElementById(a.wa.renderData.id);c||(0,_.m)((0,window.Error)("n"));return Ci.attach(a,
c)};_.S.ma("attach",fa)}Ec.style="attach";h.qe&&(l[2]=Ec,l[3]=q,l[4]=ra,h.qe("i",l),a.Sg=l[1]);var $b=function(a){var c=_.Bf.apply(_.s,[me].concat([].slice.call(arguments,0)));if(t.onready){var f=_.u,g=function(){f||(f=_.r,t.onready.call(_.s))};c.ha("ready",g);c.ha("renderstart",g)}(0,_.Hf)(c);return c}(Ec,q,ra),Ai=n;$b.ha("ready",g);$b.ha("renderstart",g);$b.ha("resize",g);var ns=a.Zo,oc=h.Db,pc=(0,window.String)(h.Bj),os=_.u;$b.ha("renderstart",f);var ms=_.u;$b.ha("ready",c);_.R.O("widget-interactive-"+
$b.id,c);_.R.O("widget-csi-tick-"+$b.id,function(a,c,f){"wdc"===a||"wci"===a?(0,_.hf)("wdc",oc,pc,f):"wje0"===a||"wji_"===a?(0,_.hf)("wje0",oc,pc,f):"wje1"===a||"wji"===a?(0,_.hf)("wje1",oc,pc,f):"wh0"==a?((0,_.jf)(oc,pc).wh0=f||(new window.Date).getTime(),(0,_.Qe)("wh0",oc,pc)):"wh1"==a&&((0,_.jf)(oc,pc).wh1=f||(new window.Date).getTime(),(0,_.Qe)("wh1",oc,pc))});l[5]=$b;h.qe&&h.qe("e",l)};g=h;if(n=g.xr)for(a=0;a<n.length;a++)(new window.Image).src=n[a];(0,_.vd)(g.Db,function(a){var c=a.userParams,
f=a.iframeNode;if((f=f&&f.parentNode)&&1===f.nodeType){f.removeAttribute("data-gwattr");var h=(0,_.Ef)(g.Ga,c);g.dm.push({element:f,Ga:h,pe:(0,_.Cf)(h,(0,_.Ef)(g.rr,c)),Sg:3,Zo:!!c["data-onload"],Fr:a})}a=g.dm;for(c=g.Ui;0<a.length;)c(a.shift())});_.Re[g.Db]=_.r;var q={J:function(a,c){var f=c||{};f.type=g.Db;var h=f.type;delete f.type;var l=("string"===typeof a?window.document.getElementById(a):a)||_.p,n={},q;for(q in f)(0,_.Da)(f,q)&&(n[q.toLowerCase()]=f[q]);n.rd=1;(0,_.Xe)(h,l,n,[],0)},go:function(a){(0,_.Oe)(a, g.Db)},b:function(){var a=(0,_.Sa)(),c;for(c in a)delete a[c]}},n=g.Db;a=(0,_.I)(_.Qa,"sws",[]);if(!(0<=_.xb.call(a,n))){if("complete"!==_.fb.readyState)try{f()}catch(t){}(0,_.$c)(f)}return q}};

_.Pu=(window.gapi||{}).load;
_.S.hj("bubble",function(a){(0,_.Pu)("iframes-styles-bubble",a)});
_.S.hj("slide-menu",function(a){(0,_.Pu)("iframes-styles-slide-menu",a)});

_.yw=function(a,c,f){a=(0,_.Ie)(a);c=(0,_.ve)(c);if(""!=a){if("inline"==a||"only"==a)return a=450,f.width&&(a=120<f.width?f.width:120),{width:a,height:_.we[c]["false"].height};if("bubble"!=a){if("none"==a)return _.we[c]["false"];if("pp"==a)return _.zw}}return _.we[c]["true"]};_.zw={width:180,height:35};_.Aw={"0":"plusone"};_.Bw=(0,_.N)("iframes/plusone/preloadUrl");_.Bw&&(_.Aw[8]=_.Bw);(0,_.Me)(_.Ae);_.Aw[1]=_.Ae;
_.Aw[2]={width:[function(a,c){return c.annotation?(0,_.yw)(c.annotation,c.size,c).width:_.we[(0,_.ve)(c.size)][(0,_.xe)(c.count,c.size)].width}],height:[function(a,c){return c.annotation?(0,_.yw)(c.annotation,c.size,c).height:_.we[(0,_.ve)(c.size)][(0,_.xe)(c.count,c.size)].height}]};_.Aw[3]=["onPlusOne",function(a){return"on"==a.state?"+1":_.s}];_.Aw[4]=["div","button"];_.Aw[6]=["onstartinteraction","onendinteraction","onpopup"];_.mb=_.nb=_.Tf.Na(_.Aw);
(0,_.O)("gapi.plusone.render",_.nb.J);(0,_.O)("gapi.plusone.go",_.nb.go);(0,_.O)("googleapisv0.plusone.render",_.mb.J);(0,_.O)("googleapisv0.plusone.go",_.mb.go);
});

// Copyright 2002-2013 Google Inc.
