document.writeln("                  <TABLE cellSpacing=3 cellPadding=3 width=130 border=0 style=\"border-collapse: collapse\" bordercolor=\"#111111\">");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"宋体\" size=\"2\">");
document.writeln("                      <span style=\"font-weight: 400; letter-spacing:6\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../organ\">");
document.writeln("                      <font color=\"#003366\">会议组织</font></a></span></font></TD>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../news\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">信息发布</font></a></span></TD>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a href=\"../prog\" style=\"text-decoration: none\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">日程安排</font></a></span></TD>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a href=\"../regis\" style=\"text-decoration: none\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">在线注册</font></a></span></TD>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a href=\"../cfp\" style=\"text-decoration: none\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">征文公告</font></a></span></TD>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a href=\"../cfe\" style=\"text-decoration: none\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">展览征集</font></a></span></TD>");
document.writeln("                    </tr>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a href=\"../spons\" style=\"text-decoration: none\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">支持赞助</font></a></span></TD></TR>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a href=\"../venue\" style=\"text-decoration: none\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">会场情况</font></a></span></TD></TR>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a href=\"../accom\" style=\"text-decoration: none\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">指定旅馆</font></a></span></TD></TR>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a href=\"../tinfo\" style=\"text-decoration: none\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">交通情况</font></a></span></TD></TR>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a style=\"text-decoration: none\" target=\"_blank\" href=\"http://210.22.80.10/Shtour/Home-1.asp\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">城市简介</font></a></span></TD></TR>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <a href=\"../contact\" style=\"text-decoration: none\">");
document.writeln("                      <font size=\"2\" color=\"#003366\">联系信息</font></a></span></TD>");
document.writeln("                    </tr>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25>");
document.writeln("                      <IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <span style=\"letter-spacing: 6\">");
document.writeln("                      <font size=\"2\">");
document.writeln("                      <a target=\"_blank\" style=\"text-decoration: none\" href=\"http://dc.library.sh.cn\">");
document.writeln("                      <font color=\"#003366\">背景知识</font></a></font></span></TD></TR></TABLE>");
