document.writeln("                  <TABLE cellSpacing=3 cellPadding=0 width=143 border=0>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\">");
document.writeln("                      <span style=\"font-size: 8pt; font-weight: 400\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../organ\">");
document.writeln("                      <font color=\"#003366\">Organization</font></a></span></font></TD>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\"><span style=\"font-size: 8pt\">");
document.writeln("                      <font color=\"#000080\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../news\">");
document.writeln("                      <font color=\"#003366\">news</font></a></font></span></font></TD>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\"><span style=\"font-size: 8pt\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../prog\">");
document.writeln("                      <font color=\"#003366\">Program</font></a></span></font></TD>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\"><span style=\"font-size: 8pt\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../regis\">");
document.writeln("                      <font color=\"#003366\">Registration</font></a></span></font></TD>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\"><span style=\"font-size: 8pt\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../cfp\">");
document.writeln("                      <font color=\"#003366\">Call for Papers</font></a></span></font></TD>");
document.writeln("                    </tr>");
document.writeln("                    <tr>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\">");
document.writeln("                      <a href=\"../cfe\" style=\"text-decoration: none\">");
document.writeln("                      <span style=\"font-size: 8pt\"><font color=\"#003366\">Call for ");
document.writeln("                      Exhibitors</font></span></a></font></TD>");
document.writeln("                    </tr>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\">");
document.writeln("                      <a href=\"../spons\" style=\"text-decoration: none\">");
document.writeln("                      <span style=\"font-size: 8pt\"><font color=\"#003366\">Sponsorship</font></span></a></font></TD></TR>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\">");
document.writeln("                      <span style=\"font-size: 8pt\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../venue\">");
document.writeln("                      <font color=\"#003366\">Venue</font></a></span></font></TD></TR>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\">");
document.writeln("                      <span style=\"font-size: 8pt\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../accom\">");
document.writeln("                      <font color=\"#003366\">Accommodation</font></a></span></font></TD></TR>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\">");
document.writeln("                      <span style=\"font-size: 8pt\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../tinfo\">");
document.writeln("                      <font color=\"#003366\">Travel ");
document.writeln("                      Information</font></a></span></font></TD></TR>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\">");
document.writeln("                      <span style=\"font-size: 8pt\">");
document.writeln("                      <a style=\"text-decoration: none\" target=\"_blank\" href=\"http://210.22.80.10/en_SHtravel/general/circs.html\">");
document.writeln("                      <font color=\"#003366\">City Tour</font></a></span></font></TD></TR>");
document.writeln("                    <TR>");
document.writeln("                      <TD vAlign=top align=left width=25><IMG height=10 ");
document.writeln("                        hspace=3 ");
document.writeln("                        src=\"../images/bullet.newsarrow.gif\" ");
document.writeln("                        width=15 vspace=3></TD>");
document.writeln("                      <TD class=txtGMPNews vAlign=top align=left>");
document.writeln("                      <font face=\"Verdana\">");
document.writeln("                      <span style=\"font-size: 8pt\"><font color=\"#000080\">");
document.writeln("                      <a style=\"text-decoration: none\" href=\"../contact\">");
document.writeln("                      <font color=\"#003366\">contact</font></a></font></span></font></TD></TR></TABLE>");
