<?xml version='1.0' encoding='UTF-8'?>
 
<xsl:stylesheet version="1.0"	
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"> 

<xsl:template name="languages">

<select name="language">
<option value="aaAfar">aa Afar</option>
<option value="abAbkhazian">ab Abkhazian</option>
<option value="afAfrikaans">af Afrikaans</option>
<option value="amAmharic">am Amharic</option>
<option value="arArabic">ar Arabic</option>
<option value="asAssamese">as Assamese</option>
<option value="ayAymara">ay Aymara</option>
<option value="azAzerbaijani">az Azerbaijani</option>
<option value="baBashkir">ba Bashkir</option>
<option value="beByelorussian">be Byelorussian</option>
<option value="bgBulgarian">bg Bulgarian</option>
<option value="bhBihari">bh Bihari</option>
<option value="biBislama">bi Bislama</option>
<option value="bnBengali">bn Bengali / Bangla</option>       
<option value="boTibetan">bo Tibetan</option>
<option value="brBreton">br Breton</option>
<option value="caCatalan">ca Catalan</option>
<option value="coCorsican">co Corsican</option>
<option value="csCzech">cs Czech</option>
<option value="cyWelsh">cy Welsh</option>
<option value="daDanish">da Danish</option>
<option value="deGerman">de German</option>
<option value="dzBhutani">dz Bhutani</option>
<option value="elGreek">el Greek</option>
<option value="enEnglish">en English</option>
<option value="eoEsperant">eo Esperanto</option>
<option value="esSpanish">es Spanish</option>
<option value="etEstonian">et Estonian</option>
<option value="euBasque">eu Basque</option>
<option value="faPersian">fa Persian</option>
<option value="fiFinnish">fi Finnish</option>
<option value="fjFiji">fj Fiji</option>
<option value="foFaeroese">fo Faeroese</option>
<option value="frFrench">fr French</option>
<option value="fyFrisian">fy Frisian</option>
<option value="gaIrish">ga Irish</option>
<option value="gdScots">gd Scots / Gaelic</option>
<option value="glGalician">gl Galician</option>
<option value="gnGuarani">gn Guarani</option>
<option value="guGujarati">gu Gujarati</option>
<option value="heHebrew">he Hebrew</option>
<option value="haHausa">ha Hausa</option>
<option value="hiHindi">hi Hindi</option>
<option value="hrCroatian">hr Croatian</option>
<option value="huHungarian">hu Hungarian</option>
<option value="hyArmenian">hy Armenian</option>
<option value="iaInterlingua">ia Interlingua</option>
<option value="idIndonesian">id Indonesian</option>
<option value="ieInterlingue">ie Interlingue</option>
<option value="ikInupiak">ik Inupiak</option>
<option value="inIndonesian">in Indonesian</option>
<option value="isIcelandic">is Icelandic</option>
<option value="itItalian">it Italian</option>
<option value="iuInuktitut">iu Inuktitut</option>
<option value="iwHebrew">iw Hebrew (obsolete)</option>   
<option value="jaJapanese">ja Japanese</option>
<option value="jiYiddish">ji Yiddish (obsolete)</option>
<option value="jwJavanese">jw Javanese</option>
<option value="kaGeorgian">ka Georgian</option>
<option value="kkKazakh">kk Kazakh</option>
<option value="klGreenlandic">kl Greenlandic</option>
<option value="kmCambodian">km Cambodian</option>
<option value="knKannada">kn Kannada</option>
<option value="koKorean">ko Korean</option>
<option value="ksKashmiri">ks Kashmiri</option>
<option value="kuKurdish">ku Kurdish</option>
<option value="kyKirghiz">ky Kirghiz</option>
<option value="laLatin">la Latin</option>
<option value="lnLingala">ln Lingala</option>
<option value="loLaothian">lo Laothian</option>
<option value="ltLithuanian">lt Lithuanian</option>
<option value="lvLatvian">lv Latvian / Lettish</option>
<option value="mgMalagasy">mg Malagasy</option>
<option value="miMaori">mi Maori</option>
<option value="mkMacedonian">mk Macedonian</option>
<option value="mlMalayalam">ml Malayalam</option>
<option value="mnMongolian">mn Mongolian</option>
<option value="moMoldavian">mo Moldavian</option>
<option value="mrMarathi">mr Marathi</option>
<option value="msMalay">ms Malay</option>
<option value="mtMaltese">mt Maltese</option>
<option value="myBurmese">my Burmese</option>
<option value="naNauru">na Nauru</option>
<option value="neNepali">ne Nepali</option>
<option value="nlDutch">nl Dutch</option>
<option value="noNorwegian">no Norwegian</option>
<option value="ocOccitan">oc Occitan</option>
<option value="omAfan">om Afan / Oromo</option>
<option value="orOriya">or Oriya</option>
<option value="paPunjabi">pa Punjabi</option>
<option value="plPolish">pl Polish</option>
<option value="psPashto">ps Pashto, Pushto</option>
<option value="ptPortuguese">pt Portuguese</option>
<option value="quQuechua">qu Quechua</option>
<option value="rmRhaeto-Romance">rm Rhaeto-Romance</option>
<option value="rnKirundi">rn Kirundi</option>
<option value="roRomanian">ro Romanian</option>
<option value="ruRussian">ru Russian</option>
<option value="rwKinyarwanda">rw Kinyarwanda</option>
<option value="saSanskrit">sa Sanskrit</option>
<option value="sdSindhi">sd Sindhi</option>
<option value="sgSangro">sg Sangro</option>
<option value="shSerbo-Croatian">sh Serbo-Croatian</option>
<option value="siSinghalese">si Singhalese</option>
<option value="skSlovak">sk Slovak</option>
<option value="slSlovenian">sl Slovenian</option>
<option value="smSamoan">sm Samoan</option>
<option value="snShona">sn Shona</option>
<option value="soSomali">so Somali</option>
<option value="sqAlbanian">sq Albanian</option>
<option value="srSerbian">sr Serbian</option>
<option value="ssSiswati">ss Siswati</option>
<option value="stSesotho">st Sesotho</option>
<option value="suSundanese">su Sundanese</option>
<option value="svSwedish">sv Swedish</option>
<option value="swSwahili">sw Swahili</option>
<option value="taTamil">ta Tamil</option>
<option value="teTegulu">te Tegulu</option>
<option value="tgTajik">tg Tajik</option>
<option value="thThai">th Thai</option>
<option value="tiTigrinya">ti Tigrinya</option>
<option value="tkTurkmen">tk Turkmen</option>
<option value="tlTagalog">tl Tagalog</option>
<option value="tnSetswana">tn Setswana</option>
<option value="toTonga">to Tonga</option>
<option value="trTurkish">tr Turkish</option>
<option value="tsTsonga">ts Tsonga</option>
<option value="ttTatar">tt Tatar</option>
<option value="twTwi">tw Twi</option>
<option value="ugUigur">ug Uigur</option>
<option value="ukUkrainian">uk Ukrainian</option>
<option value="urUrdu">ur Urdu</option>
<option value="uzUzbek">uz Uzbek</option>
<option value="viVietnamese">vi Vietnamese</option>
<option value="voVolapuk">vo Volapuk</option>
<option value="woWolof">wo Wolof</option>
<option value="xhXhosa">xh Xhosa</option>
<option value="yoYoruba">yo Yoruba</option>
<option value="zaZuang">za Zuang</option>
<option value="zhChinese">zh Chinese</option>
<option value="zuZulu">zu Zulu</option>
</select>

</xsl:template>

</xsl:stylesheet>
